"use client";

import { useEffect, useMemo, useState } from "react";

export type InvoiceCustomerOption = {
  addressExtra?: string;
  city?: string;
  country?: string;
  customerNumber?: string;
  id: string;
  name: string;
  postalCode?: string;
  street?: string;
};

type InvoiceCustomerCopy = {
  addressExtra: string;
  address: string;
  autoGenerated: string;
  cancel: string;
  city: string;
  company: string;
  companyName: string;
  country: string;
  createAsCustomer: string;
  createCustomer: string;
  customer: string;
  customerNotFoundPrompt: string;
  customerNumber: string;
  customerType: string;
  date: string;
  deliveryDate: string;
  deliveryOrService: string;
  deliveryPeriod: string;
  due: string;
  email: string;
  invoiceNumber: string;
  issueDate: string;
  noServiceDate: string;
  person: string;
  phone: string;
  postalCode: string;
  save: string;
  selectCustomer: string;
  serviceDate: string;
  servicePeriod: string;
  street: string;
  useWithoutMasterData: string;
};

const createdCustomerStorageKey = "ctox:business:invoice-created-customers";

export function InvoiceCustomerEditor({
  copy,
  customers,
  initialCustomerId,
  invoice
}: {
  copy: InvoiceCustomerCopy;
  customers: InvoiceCustomerOption[];
  initialCustomerId: string;
  invoice: {
    dueDate: string;
    issueDate: string;
    number: string;
    serviceDate?: string;
  };
}) {
  const [customerList, setCustomerList] = useState(customers);
  const [selectedCustomerId, setSelectedCustomerId] = useState(initialCustomerId);
  const selectedCustomer = customerList.find((customer) => customer.id === selectedCustomerId) ?? customerList[0];
  const [query, setQuery] = useState(selectedCustomer?.name ?? "");
  const [isOpen, setIsOpen] = useState(false);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [serviceKind, setServiceKind] = useState("delivery-date");
  const [serviceDate, setServiceDate] = useState(invoice.serviceDate ?? invoice.issueDate);
  const [draft, setDraft] = useState(() => customerDraft(selectedCustomer, selectedCustomer?.name ?? ""));

  const matches = useMemo(() => {
    const normalized = normalize(query);
    if (selectedCustomer && normalized === normalize(selectedCustomer.name)) return customerList;
    if (!normalized) return customerList;
    return customerList.filter((customer) => normalize(customer.name).includes(normalized));
  }, [customerList, query, selectedCustomer]);
  const exactMatch = customerList.find((customer) => normalize(customer.name) === normalize(query));
  const showMissingCustomerPrompt = query.trim().length > 2 && !exactMatch && !isCreateOpen;
  const visibleCustomer = selectedCustomerId === "manual"
    ? { ...draft, name: query, id: "manual" }
    : selectedCustomer;

  useEffect(() => {
    const stored = readStoredCustomers();
    if (stored.length === 0) return;
    setCustomerList((current) => mergeCustomers(stored, current));
  }, []);

  const selectCustomer = (customer: InvoiceCustomerOption) => {
    setSelectedCustomerId(customer.id);
    setQuery(customer.name);
    setDraft(customerDraft(customer, customer.name));
    setIsOpen(false);
  };

  const openCreateCustomer = () => {
    const base = customerDraft(undefined, query);
    setDraft({ ...base, name: query.trim() || base.name });
    setIsCreateOpen(true);
    setIsOpen(false);
  };

  const saveCustomer = () => {
    const name = draft.name.trim();
    if (!name) return;
    const customer: InvoiceCustomerOption = {
      ...draft,
      customerNumber: draft.customerNumber || copy.autoGenerated,
      id: `customer-${Date.now()}`,
      name
    };
    setCustomerList((current) => [customer, ...current]);
    writeStoredCustomer(customer);
    selectCustomer(customer);
    setIsCreateOpen(false);
  };

  return (
    <>
      <section className="invoice-editor-card invoice-editor-grid invoice-customer-card">
        <label className="invoice-field invoice-customer-combobox">
          <span>{copy.customer}</span>
          <input
            aria-label={copy.selectCustomer}
            onChange={(event) => {
              const nextValue = event.target.value;
              setQuery(nextValue);
              setIsOpen(true);
              const match = customerList.find((customer) => normalize(customer.name) === normalize(nextValue));
              if (match) selectCustomer(match);
              else {
                setSelectedCustomerId("manual");
                setDraft(customerDraft(undefined, nextValue));
              }
            }}
            onFocus={() => setIsOpen(true)}
            type="text"
            value={query}
          />
          <button aria-label={copy.selectCustomer} onClick={() => setIsOpen((value) => !value)} type="button" />
          {isOpen ? (
            <div className="invoice-customer-menu">
              {matches.map((customer) => (
                <button key={customer.id} onClick={() => selectCustomer(customer)} type="button">
                  <strong>{customer.name}</strong>
                  <span>{[customer.customerNumber, customer.city, customer.country].filter(Boolean).join(" · ")}</span>
                </button>
              ))}
              <button className="invoice-customer-create-option" onClick={openCreateCustomer} type="button">
                + {copy.createCustomer}
              </button>
            </div>
          ) : null}
        </label>
        <StaticInvoiceField label={copy.invoiceNumber} value={invoice.number} />
        {showMissingCustomerPrompt ? (
          <div className="invoice-customer-prompt">
            <span>{copy.customerNotFoundPrompt}</span>
            <button onClick={openCreateCustomer} type="button">{copy.createAsCustomer}</button>
            <button onClick={() => setIsOpen(false)} type="button">{copy.useWithoutMasterData}</button>
          </div>
        ) : null}
        <StaticInvoiceField label={copy.addressExtra} muted value={visibleCustomer?.addressExtra || copy.addressExtra} />
        <StaticInvoiceField label={copy.customerNumber} muted value={visibleCustomer?.customerNumber || copy.autoGenerated} />
        <StaticInvoiceField label={copy.street} value={visibleCustomer?.street || ""} />
        <StaticInvoiceField label={copy.issueDate} value={invoice.issueDate} />
        <div className="invoice-editor-split">
          <StaticInvoiceField label={copy.postalCode} value={visibleCustomer?.postalCode || ""} />
          <StaticInvoiceField label={copy.city} value={visibleCustomer?.city || ""} />
        </div>
        <div className="invoice-editor-split invoice-service-split">
          <label className="invoice-field invoice-select-field">
            <span>{copy.deliveryOrService}</span>
            <select aria-label={copy.deliveryOrService} onChange={(event) => setServiceKind(event.target.value)} value={serviceKind}>
              <option value="delivery-date">{copy.deliveryDate}</option>
              <option value="service-date">{copy.serviceDate}</option>
              <option value="delivery-period">{copy.deliveryPeriod}</option>
              <option value="service-period">{copy.servicePeriod}</option>
              <option value="none">{copy.noServiceDate}</option>
            </select>
          </label>
          <label className="invoice-field invoice-date-field">
            <span>{copy.date}</span>
            <input
              aria-label={copy.date}
              disabled={serviceKind === "none"}
              onChange={(event) => setServiceDate(event.target.value)}
              type="date"
              value={serviceDate}
            />
          </label>
        </div>
        <StaticInvoiceField className="invoice-field-wide" label={copy.country} value={visibleCustomer?.country || "Deutschland"} />
        <StaticInvoiceField label={copy.due} value={invoice.dueDate} />
      </section>

      {isCreateOpen ? (
        <div className="invoice-customer-overlay" role="dialog" aria-modal="true" aria-label={copy.createCustomer}>
          <button className="invoice-customer-backdrop" onClick={() => setIsCreateOpen(false)} type="button" />
          <section className="invoice-customer-drawer">
            <header>
              <h3>{copy.createCustomer}</h3>
              <button aria-label={copy.cancel} onClick={() => setIsCreateOpen(false)} type="button">x</button>
            </header>
            <div className="invoice-customer-type" aria-label={copy.customerType}>
              <span>{copy.customerType}</span>
              <label><input checked readOnly type="radio" /> {copy.company}</label>
              <label><input readOnly type="radio" /> {copy.person}</label>
            </div>
            <label className="drawer-field">
              {copy.companyName}
              <input onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} value={draft.name} />
            </label>
            <h4>{copy.address}</h4>
            <label className="drawer-field">
              {copy.addressExtra}
              <input onChange={(event) => setDraft((current) => ({ ...current, addressExtra: event.target.value }))} value={draft.addressExtra ?? ""} />
            </label>
            <label className="drawer-field">
              {copy.street}
              <input onChange={(event) => setDraft((current) => ({ ...current, street: event.target.value }))} value={draft.street ?? ""} />
            </label>
            <div className="drawer-field-grid">
              <label className="drawer-field">
                {copy.postalCode}
                <input onChange={(event) => setDraft((current) => ({ ...current, postalCode: event.target.value }))} value={draft.postalCode ?? ""} />
              </label>
              <label className="drawer-field">
                {copy.city}
                <input onChange={(event) => setDraft((current) => ({ ...current, city: event.target.value }))} value={draft.city ?? ""} />
              </label>
            </div>
            <label className="drawer-field">
              {copy.country}
              <input onChange={(event) => setDraft((current) => ({ ...current, country: event.target.value }))} value={draft.country ?? ""} />
            </label>
            <div className="invoice-customer-additions">
              <button type="button">+ {copy.email}</button>
              <button type="button">+ {copy.phone}</button>
            </div>
            <footer>
              <button onClick={() => setIsCreateOpen(false)} type="button">{copy.cancel}</button>
              <button className="drawer-primary" onClick={saveCustomer} type="button">{copy.save}</button>
            </footer>
          </section>
        </div>
      ) : null}
    </>
  );
}

function StaticInvoiceField({
  className,
  label,
  muted,
  value
}: {
  className?: string;
  label: string;
  muted?: boolean;
  value: string;
}) {
  return (
    <div className={`invoice-field ${className ?? ""} ${muted ? "is-muted" : ""}`.trim()}>
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}

function customerDraft(customer: InvoiceCustomerOption | undefined, fallbackName: string) {
  return {
    addressExtra: customer?.addressExtra ?? "",
    city: customer?.city ?? "",
    country: customer?.country ?? "Deutschland",
    customerNumber: customer?.customerNumber ?? "",
    name: customer?.name ?? fallbackName,
    postalCode: customer?.postalCode ?? "",
    street: customer?.street ?? ""
  };
}

function normalize(value: string) {
  return value.trim().toLocaleLowerCase("de-DE");
}

function readStoredCustomers() {
  try {
    const value = window.localStorage.getItem(createdCustomerStorageKey);
    const parsed = value ? JSON.parse(value) : [];
    return Array.isArray(parsed) ? parsed.filter(isCustomerOption) : [];
  } catch {
    return [];
  }
}

function writeStoredCustomer(customer: InvoiceCustomerOption) {
  const next = mergeCustomers([customer], readStoredCustomers()).slice(0, 25);
  window.localStorage.setItem(createdCustomerStorageKey, JSON.stringify(next));
}

function mergeCustomers(primary: InvoiceCustomerOption[], secondary: InvoiceCustomerOption[]) {
  const seen = new Set<string>();
  return [...primary, ...secondary].filter((customer) => {
    const key = normalize(customer.name || customer.id);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function isCustomerOption(value: unknown): value is InvoiceCustomerOption {
  return Boolean(value && typeof value === "object" && "id" in value && "name" in value);
}
