// Origin: CTOX
// License: Apache-2.0

pub(crate) mod approval_nag;
pub mod channels;
pub mod follow_up;
pub mod plan;
pub mod queue;
pub mod review;
pub mod schedule;
pub mod strategy;
pub(crate) mod ticket_adapters;
pub(crate) mod ticket_gateway;
pub(crate) mod ticket_local_native;
pub(crate) mod ticket_protocol;
pub(crate) mod ticket_translation;
pub(crate) mod ticket_zammad_native;
pub mod tickets;
pub mod verification;
