const jsonObject = { type: 'object', additionalProperties: true };
const stringArray = { type: 'array', items: { type: 'string' } };

const commandSchema = {
  version: 1,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 128 },
    command_id: { type: 'string' },
    module: { type: 'string' },
    command_type: { type: 'string' },
    record_id: { type: 'string' },
    status: { type: 'string' },
    inbound_channel: { type: 'string' },
    payload: jsonObject,
    client_context: jsonObject,
    result: jsonObject,
    task_id: { type: 'string' },
    task_status: { type: 'string' },
    updated_at_ms: { type: 'number' },
  },
  required: ['id', 'command_id', 'module', 'command_type', 'status', 'updated_at_ms'],
  additionalProperties: true,
};

const queueTaskSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 128 },
    title: { type: 'string' },
    status: { type: 'string' },
    module: { type: 'string' },
    source_module: { type: 'string' },
    inbound_channel: { type: 'string' },
    updated_at_ms: { type: 'number' },
  },
  required: ['id', 'title', 'status', 'module'],
  additionalProperties: true,
};

function threadsRecordSchema(properties, required = [], indexes = []) {
  return {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: { type: 'string', maxLength: 256 },
      is_deleted: { type: 'boolean' },
      created_at_ms: { type: 'number' },
      updated_at_ms: { type: 'number' },
      deleted_at_ms: { type: 'number' },
      ...properties,
    },
    required: ['id', 'updated_at_ms', ...required],
    indexes: ['updated_at_ms', ['is_deleted', 'updated_at_ms'], ...indexes],
    additionalProperties: true,
  };
}

export const collections = {
  business_commands: commandSchema,
  ctox_queue_tasks: queueTaskSchema,
  user_threads: threadsRecordSchema({
    thread_id: { type: 'string' },
    title: { type: 'string' },
    kind: { type: 'string' },
    status: { type: 'string' },
    participant_ids: stringArray,
    watcher_user_ids: stringArray,
    owner_user_id: { type: 'string' },
    created_by_id: { type: 'string' },
    assigned_user_id: { type: 'string' },
    source_module: { type: 'string' },
    source_record_type: { type: 'string' },
    source_record_id: { type: 'string' },
    source_label: { type: 'string' },
    source_deep_link: { type: 'string' },
    last_message_id: { type: 'string' },
    last_message_at_ms: { type: 'number' },
    pending_approval_count: { type: 'number' },
    snoozed_until_ms: { type: 'number' },
    archived_at_ms: { type: 'number' },
    last_seen_by_user: jsonObject,
    metadata: jsonObject,
  }, ['title', 'status', 'participant_ids'], [
    'status',
    'owner_user_id',
    'assigned_user_id',
    'watcher_user_ids',
    'source_module',
    'source_record_id',
    ['status', 'updated_at_ms'],
  ]),
  user_thread_messages: threadsRecordSchema({
    message_id: { type: 'string' },
    thread_id: { type: 'string' },
    kind: { type: 'string' },
    author_user_id: { type: 'string' },
    author_display_name: { type: 'string' },
    target_user_ids: stringArray,
    body: { type: 'string' },
    source_module: { type: 'string' },
    source_record_type: { type: 'string' },
    source_record_id: { type: 'string' },
    source_label: { type: 'string' },
    source_deep_link: { type: 'string' },
    approval_request_id: { type: 'string' },
    command_id: { type: 'string' },
    metadata: jsonObject,
  }, ['thread_id', 'kind', 'body'], [
    'thread_id',
    'author_user_id',
    'approval_request_id',
    ['thread_id', 'created_at_ms'],
  ]),
  user_thread_links: threadsRecordSchema({
    thread_id: { type: 'string' },
    source_module: { type: 'string' },
    source_record_type: { type: 'string' },
    source_record_id: { type: 'string' },
    source_label: { type: 'string' },
    link_role: { type: 'string' },
    link_type: { type: 'string' },
    command_id: { type: 'string' },
    task_id: { type: 'string' },
    case_id: { type: 'string' },
    deep_link: { type: 'string' },
    label: { type: 'string' },
    context: jsonObject,
  }, ['thread_id'], [
    'thread_id',
    'source_module',
    'source_record_id',
  ]),
  user_notifications: threadsRecordSchema({
    notification_id: { type: 'string' },
    user_id: { type: 'string' },
    thread_id: { type: 'string' },
    message_id: { type: 'string' },
    approval_request_id: { type: 'string' },
    notification_type: { type: 'string' },
    status: { type: 'string' },
    title: { type: 'string' },
    body_preview: { type: 'string' },
    source_module: { type: 'string' },
    source_record_id: { type: 'string' },
  }, ['user_id', 'thread_id', 'notification_type', 'status'], [
    'user_id',
    'status',
    'thread_id',
    ['user_id', 'status', 'updated_at_ms'],
  ]),
  ctox_task_approval_requests: threadsRecordSchema({
    approval_request_id: { type: 'string' },
    thread_id: { type: 'string' },
    status: { type: 'string' },
    requester_user_id: { type: 'string' },
    requester_display_name: { type: 'string' },
    reviewer_user_id: { type: 'string' },
    reviewer_display_name: { type: 'string' },
    prompt: { type: 'string' },
    instruction: { type: 'string' },
    target_command_type: { type: 'string' },
    target_module: { type: 'string' },
    target_record_id: { type: 'string' },
    source_module: { type: 'string' },
    source_record_type: { type: 'string' },
    source_record_id: { type: 'string' },
    source_label: { type: 'string' },
    source_deep_link: { type: 'string' },
    requested_at_ms: { type: 'number' },
    decided_at_ms: { type: 'number' },
    decision_by_id: { type: 'string' },
    decision_note: { type: 'string' },
    approved_command_id: { type: 'string' },
    approved_task_id: { type: 'string' },
    target_payload: jsonObject,
    source_context: jsonObject,
    client_context: jsonObject,
  }, ['thread_id', 'status', 'requester_user_id', 'reviewer_user_id', 'prompt'], [
    'status',
    'requester_user_id',
    'reviewer_user_id',
    'thread_id',
    ['reviewer_user_id', 'status', 'updated_at_ms'],
  ]),
};

export const migrationStrategies = {
  business_commands: {
    1: (oldDoc) => ({
      ...oldDoc,
      inbound_channel: oldDoc.inbound_channel || oldDoc.module || '',
    }),
  },
};
