//! Build script: compile every `.cu` file under `kernels/` to PTX via
//! `nvcc`, then generate an `OUT_DIR/ptx_registry.rs` file that holds
//! each PTX blob as a `const &[u8]` via `include_bytes!`. Kernel
//! wrappers in `src/kernels/` then `include!` the registry and load
//! the relevant blob at first call.
//!
//! Gated on the `cuda` Cargo feature — when off this script is a
//! no-op so the crate still compiles on non-CUDA hosts (Mac dev,
//! CI without nvcc).
//!
//! Env overrides:
//!   CTOX_CUDA_SM=86        Target SM capability (default: 86 = A6000).
//!                          Set to `80,86,89,90` for multi-arch fatbin,
//!                          but for now we build single-arch PTX because
//!                          PTX embeds sm at load time via cudarc.
//!   NVCC=/path/to/nvcc     Override nvcc binary location.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    // When `cuda` feature is off, the crate compiles to stubs and
    // needs no PTX — write an empty registry so `include!` still
    // resolves and bail.
    let cuda_on = env::var("CARGO_FEATURE_CUDA").is_ok();
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let registry_path = out_dir.join("ptx_registry.rs");

    if !cuda_on {
        fs::write(
            &registry_path,
            "// AUTO-GENERATED: cuda feature is off, registry is empty.\n\
             pub struct PtxBlob { pub name: &'static str, pub bytes: &'static [u8] }\n\
             pub static PTX_BLOBS: &[PtxBlob] = &[];\n",
        )
        .expect("write empty ptx_registry");
        return;
    }

    // Kernels live under CARGO_MANIFEST_DIR/kernels/*.cu.
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));
    let kernels_dir = manifest_dir.join("kernels");
    let ptx_dir = out_dir.join("ptx");
    fs::create_dir_all(&ptx_dir).expect("mkdir ptx");

    println!("cargo:rerun-if-changed=kernels");
    println!("cargo:rerun-if-env-changed=CTOX_CUDA_SM");
    println!("cargo:rerun-if-env-changed=NVCC");

    let sm = env::var("CTOX_CUDA_SM").unwrap_or_else(|_| "86".to_string());
    let nvcc = env::var("NVCC").unwrap_or_else(|_| "nvcc".to_string());

    // Collect .cu files.
    let mut cu_files: Vec<PathBuf> = Vec::new();
    if kernels_dir.is_dir() {
        for entry in fs::read_dir(&kernels_dir).expect("read kernels dir") {
            let entry = entry.expect("dir entry");
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("cu") {
                println!("cargo:rerun-if-changed={}", path.display());
                cu_files.push(path);
            }
        }
    }
    cu_files.sort();

    // Compile each .cu → .ptx.
    let mut compiled: Vec<(String, PathBuf)> = Vec::new();
    for cu in &cu_files {
        let stem = cu
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("kernel stem");
        let ptx_out = ptx_dir.join(format!("{}.ptx", stem));

        let status = Command::new(&nvcc)
            .arg("--ptx")
            .arg("-arch")
            .arg(format!("sm_{}", sm))
            .arg("-O3")
            .arg("-std=c++17")
            // Allow `extern "C"` entry points without name mangling and
            // print detailed register usage for tuning.
            .arg("--ptxas-options=-v")
            .arg("-o")
            .arg(&ptx_out)
            .arg(cu)
            .status()
            .unwrap_or_else(|e| {
                panic!(
                    "nvcc not runnable ({}). Set NVCC=/path/to/nvcc or install CUDA \
                     toolkit. err={}",
                    &nvcc, e
                )
            });
        if !status.success() {
            panic!("nvcc failed compiling {}", cu.display());
        }

        compiled.push((stem.to_string(), ptx_out));
    }

    // Emit registry.
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs — do not edit.\n");
    out.push_str("// Source: kernels/*.cu, compiled via nvcc → PTX, embedded via include_bytes!\n\n");
    out.push_str("pub struct PtxBlob {\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub bytes: &'static [u8],\n");
    out.push_str("}\n\n");

    // Per-kernel named consts so wrappers can refer to them by symbol.
    for (name, path) in &compiled {
        let upper = name.to_uppercase();
        // Use raw-string path literal so Windows backslashes (if any)
        // don't need escaping. OUT_DIR is always absolute.
        out.push_str(&format!(
            "pub const {}_PTX: &[u8] = include_bytes!(r\"{}\");\n",
            upper,
            path.display()
        ));
    }
    out.push('\n');

    out.push_str("pub static PTX_BLOBS: &[PtxBlob] = &[\n");
    for (name, _) in &compiled {
        let upper = name.to_uppercase();
        out.push_str(&format!(
            "    PtxBlob {{ name: \"{}\", bytes: {}_PTX }},\n",
            name, upper
        ));
    }
    out.push_str("];\n");

    fs::write(&registry_path, out).expect("write ptx_registry.rs");
}
