const customerAccountSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    name: { type: 'string' },
    domain: { type: 'string' },
    website_url: { type: 'string' },
    linkedin_url: { type: 'string' },
    x_url: { type: 'string' },
    account_status: { type: 'string' },
    customer_stage: { type: 'string' },
    account_owner_id: { type: 'string' },
    annual_recurring_revenue_cents: { type: 'number' },
    currency: { type: 'string' },
    employee_count: { type: 'number' },
    industry: { type: 'string' },
    address: { type: 'object', additionalProperties: true },
    ideal_customer_profile: { type: 'boolean' },
    source: { type: 'string' },
    source_record_id: { type: 'string' },
    last_activity_at_ms: { type: 'number' },
    next_action_at_ms: { type: 'number' },
    health_status: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    search_text: { type: 'string' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'name', 'account_status', 'customer_stage', 'health_status', 'search_text', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'domain',
    'account_owner_id',
    'account_status',
    'customer_stage',
    'health_status',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['account_owner_id', 'updated_at_ms'],
    ['customer_stage', 'updated_at_ms'],
    ['health_status', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const customerContactSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    account_id: { type: 'string' },
    first_name: { type: 'string' },
    last_name: { type: 'string' },
    email: { type: 'string' },
    phone: { type: 'string' },
    job_title: { type: 'string' },
    city: { type: 'string' },
    linkedin_url: { type: 'string' },
    x_url: { type: 'string' },
    is_primary_contact: { type: 'boolean' },
    contact_owner_id: { type: 'string' },
    last_activity_at_ms: { type: 'number' },
    source: { type: 'string' },
    source_record_id: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    search_text: { type: 'string' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'account_id', 'first_name', 'last_name', 'email', 'is_primary_contact', 'search_text', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'account_id',
    'email',
    'contact_owner_id',
    'is_primary_contact',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['account_id', 'updated_at_ms'],
    ['contact_owner_id', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const customerOpportunitySchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    name: { type: 'string' },
    account_id: { type: 'string' },
    primary_contact_id: { type: 'string' },
    owner_id: { type: 'string' },
    opportunity_type: { type: 'string' },
    stage: { type: 'string' },
    amount_cents: { type: 'number' },
    currency: { type: 'string' },
    close_date_ms: { type: 'number' },
    probability: { type: 'number' },
    position: { type: 'number' },
    last_stage_changed_at_ms: { type: 'number' },
    lost_reason: { type: 'string' },
    source: { type: 'string' },
    source_record_id: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    search_text: { type: 'string' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'name', 'account_id', 'stage', 'opportunity_type', 'amount_cents', 'currency', 'position', 'search_text', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'account_id',
    'primary_contact_id',
    'owner_id',
    'stage',
    'opportunity_type',
    'close_date_ms',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['stage', 'position'],
    ['owner_id', 'updated_at_ms'],
    ['account_id', 'updated_at_ms'],
    ['opportunity_type', 'close_date_ms'],
  ],
  additionalProperties: true,
};

const customerTaskSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    title: { type: 'string' },
    body: { type: 'string' },
    status: { type: 'string' },
    due_at_ms: { type: 'number' },
    assignee_id: { type: 'string' },
    account_id: { type: 'string' },
    contact_id: { type: 'string' },
    opportunity_id: { type: 'string' },
    position: { type: 'number' },
    payload: { type: 'object', additionalProperties: true },
    search_text: { type: 'string' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'title', 'status', 'search_text', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'status',
    'assignee_id',
    'account_id',
    'contact_id',
    'opportunity_id',
    'due_at_ms',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['assignee_id', 'due_at_ms'],
    ['account_id', 'updated_at_ms'],
    ['opportunity_id', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const customerNoteSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    title: { type: 'string' },
    body: { type: 'string' },
    body_format: { type: 'string' },
    author_id: { type: 'string' },
    account_id: { type: 'string' },
    contact_id: { type: 'string' },
    opportunity_id: { type: 'string' },
    linked_note_id: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    search_text: { type: 'string' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'title', 'body', 'body_format', 'search_text', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'author_id',
    'account_id',
    'contact_id',
    'opportunity_id',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['account_id', 'updated_at_ms'],
    ['opportunity_id', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const customerActivitySchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 220 },
    happens_at_ms: { type: 'number' },
    activity_type: { type: 'string' },
    name: { type: 'string' },
    properties: { type: 'object', additionalProperties: true },
    actor_id: { type: 'string' },
    account_id: { type: 'string' },
    contact_id: { type: 'string' },
    opportunity_id: { type: 'string' },
    communication_message_key: { type: 'string' },
    linked_record_type: { type: 'string' },
    linked_record_id: { type: 'string' },
    linked_record_name: { type: 'string' },
    source: { type: 'string' },
    source_record_id: { type: 'string' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
  },
  required: ['id', 'happens_at_ms', 'activity_type', 'name', 'properties', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'activity_type',
    'account_id',
    'contact_id',
    'opportunity_id',
    'communication_message_key',
    'happens_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['is_deleted', 'happens_at_ms'],
    ['account_id', 'happens_at_ms'],
    ['opportunity_id', 'happens_at_ms'],
  ],
  additionalProperties: true,
};

const customerFileSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    title: { type: 'string' },
    file_url: { type: 'string' },
    filename: { type: 'string' },
    mime_type: { type: 'string' },
    size_bytes: { type: 'number' },
    account_id: { type: 'string' },
    contact_id: { type: 'string' },
    opportunity_id: { type: 'string' },
    document_id: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'title', 'filename', 'mime_type', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'account_id',
    'contact_id',
    'opportunity_id',
    'document_id',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const customerViewSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    name: { type: 'string' },
    object_type: { type: 'string' },
    view_type: { type: 'string' },
    visibility: { type: 'string' },
    owner_id: { type: 'string' },
    column_order: { type: 'array', items: { type: 'string' } },
    visible_columns: { type: 'array', items: { type: 'string' } },
    group_by_field: { type: 'string' },
    aggregate_field: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'name', 'object_type', 'view_type', 'visibility', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'object_type',
    'view_type',
    'visibility',
    'owner_id',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['object_type', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const customerViewFilterSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    view_id: { type: 'string' },
    field_name: { type: 'string' },
    operator: { type: 'string' },
    value: { type: 'string' },
    value_json: { type: 'object', additionalProperties: true },
    position: { type: 'number' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'view_id', 'field_name', 'operator', 'position', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: ['view_id', 'field_name', ['is_deleted', 'updated_at_ms'], ['view_id', 'position']],
  additionalProperties: true,
};

const customerViewSortSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    view_id: { type: 'string' },
    field_name: { type: 'string' },
    direction: { type: 'string' },
    position: { type: 'number' },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'view_id', 'field_name', 'direction', 'position', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: ['view_id', 'field_name', ['is_deleted', 'updated_at_ms'], ['view_id', 'position']],
  additionalProperties: true,
};

const customerImportBatchSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    source: { type: 'string' },
    source_record_id: { type: 'string' },
    source_filename: { type: 'string' },
    status: { type: 'string' },
    object_type: { type: 'string' },
    imported_count: { type: 'number' },
    skipped_count: { type: 'number' },
    failed_count: { type: 'number' },
    dedupe_count: { type: 'number' },
    payload: { type: 'object', additionalProperties: true },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'source', 'status', 'object_type', 'imported_count', 'skipped_count', 'failed_count', 'dedupe_count', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: ['source', 'source_record_id', 'status', 'object_type', 'updated_at_ms', ['is_deleted', 'updated_at_ms']],
  additionalProperties: true,
};

const customerDedupeCandidateSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 220 },
    object_type: { type: 'string' },
    match_key: { type: 'string' },
    match_type: { type: 'string' },
    source_record_id: { type: 'string' },
    existing_record_id: { type: 'string' },
    import_batch_id: { type: 'string' },
    status: { type: 'string' },
    confidence: { type: 'number' },
    decision: { type: 'string' },
    decided_by_id: { type: 'string' },
    decided_at_ms: { type: 'number' },
    payload: { type: 'object', additionalProperties: true },
    is_deleted: { type: 'boolean' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
    deleted_at_ms: { type: 'number' },
  },
  required: ['id', 'object_type', 'match_key', 'match_type', 'status', 'confidence', 'is_deleted', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'object_type',
    'match_key',
    'match_type',
    'status',
    'import_batch_id',
    'updated_at_ms',
    ['is_deleted', 'updated_at_ms'],
    ['object_type', 'match_key'],
    ['status', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

// Record collections that several people edit concurrently opt into the
// field-merge conflict strategy: concurrent edits to DIFFERENT fields of the
// same record both survive (three-way merge in the browser store); true
// same-field conflicts keep local-wins. `conflictStrategy` is a sibling of
// `schema` — deliberately outside the schema object, so schema hashes are
// unaffected (the shell, the hash generator, and the native peer all read
// `definition.schema || definition`).
export const collections = {
    customer_accounts: { schema: customerAccountSchema, conflictStrategy: 'field-merge' },
  customer_contacts: { schema: customerContactSchema, conflictStrategy: 'field-merge' },
  customer_opportunities: { schema: customerOpportunitySchema, conflictStrategy: 'field-merge' },
  customer_tasks: { schema: customerTaskSchema, conflictStrategy: 'field-merge' },
  customer_notes: { schema: customerNoteSchema, conflictStrategy: 'field-merge' },
  customer_activities: customerActivitySchema,
  customer_files: customerFileSchema,
  customer_views: customerViewSchema,
  customer_view_filters: customerViewFilterSchema,
  customer_view_sorts: customerViewSortSchema,
  customer_import_batches: customerImportBatchSchema,
  customer_dedupe_candidates: customerDedupeCandidateSchema,
};

export const migrationStrategies = {
  };
