// Generated by ctox-sync/tools/generate-contracts.mjs. Do not edit.
// Fixture SHA-256: 1d9a7f2531cc70d942a9c3763f0d47076a9c732ff2712f84bdcfcf94d429e249
use serde::{Deserialize, Serialize};
pub const CTOX_BUSINESS_DATA_PROTOCOL_VERSION: u32 = 1;
pub const CTOX_BUSINESS_DATA_MAX_PAGE_DOCUMENTS: u32 = 200;
pub const CTOX_BUSINESS_DATA_MAX_SNAPSHOT_BYTES: u32 = 2097152;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum NativeBusinessDataCommandStatus {
    Pending,
    Completed,
    Failed,
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum NativeBusinessDataErrorCode {
    InvalidRequest,
    Unsupported,
    Unauthorized,
    UnknownSession,
    StaleGeneration,
    Disconnected,
    Revoked,
    SchemaMismatch,
    LimitExceeded,
    ResetRequired,
    Internal,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataSessionRef {
    pub handle: String,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub generation: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataBinding {
    pub target_id: String,
    pub instance_id: String,
    pub user_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataQuery {
    pub collection: String,
    pub scope: NativeBusinessDataScope,
    pub query: serde_json::Value,
    pub page_size: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataRecord {
    pub document_id: String,
    pub document: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataCommand {
    pub command_id: String,
    pub command_type: String,
    pub payload: serde_json::Value,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataCommandState {
    pub command_id: String,
    pub status: NativeBusinessDataCommandStatus,
    pub result: Option<serde_json::Value>,
    pub error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataRequest {
    pub version: u32,
    pub request_id: String,
    pub operation: NativeBusinessDataOperation,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataResponse {
    pub version: u32,
    pub request_id: String,
    pub result: NativeBusinessDataResult,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct NativeBusinessDataEvent {
    pub version: u32,
    pub session: NativeBusinessDataSessionRef,
    pub subscription_id: String,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub sequence: u64,
    pub payload: NativeBusinessDataEventPayload,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum NativeBusinessDataScope {
    Instance {},
    Project {
        project_id: String,
    },
    Thread {
        project_id: String,
        thread_id: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum NativeBusinessDataSessionState {
    Resolving {
        session: NativeBusinessDataSessionRef,
        target_id: String,
    },
    Ready {
        session: NativeBusinessDataSessionRef,
        binding: NativeBusinessDataBinding,
    },
    Disconnected {
        session: NativeBusinessDataSessionRef,
        binding: NativeBusinessDataBinding,
    },
    Revoked {
        session: NativeBusinessDataSessionRef,
        reason: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum NativeBusinessDataOperation {
    Open {
        target_id: String,
    },
    Status {
        session: NativeBusinessDataSessionRef,
    },
    Close {
        session: NativeBusinessDataSessionRef,
    },
    Query {
        session: NativeBusinessDataSessionRef,
        query: NativeBusinessDataQuery,
        page_cursor: Option<String>,
    },
    Watch {
        session: NativeBusinessDataSessionRef,
        query: NativeBusinessDataQuery,
        resume_cursor: Option<String>,
    },
    Unwatch {
        session: NativeBusinessDataSessionRef,
        subscription_id: String,
    },
    SubmitCommand {
        session: NativeBusinessDataSessionRef,
        command: NativeBusinessDataCommand,
    },
    ObserveCommand {
        session: NativeBusinessDataSessionRef,
        command_id: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum NativeBusinessDataResult {
    Session {
        state: NativeBusinessDataSessionState,
    },
    Page {
        session: NativeBusinessDataSessionRef,
        snapshot_id: String,
        records: Vec<NativeBusinessDataRecord>,
        next_page_cursor: Option<String>,
        snapshot_complete: bool,
    },
    Subscribed {
        session: NativeBusinessDataSessionRef,
        subscription_id: String,
    },
    Command {
        session: NativeBusinessDataSessionRef,
        state: NativeBusinessDataCommandState,
    },
    Closed {
        session: NativeBusinessDataSessionRef,
    },
    Unwatched {
        session: NativeBusinessDataSessionRef,
        subscription_id: String,
    },
    Rejected {
        code: NativeBusinessDataErrorCode,
        message: String,
        retryable: bool,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum NativeBusinessDataEventPayload {
    SnapshotStart {
        snapshot_id: String,
    },
    SnapshotPage {
        snapshot_id: String,
        records: Vec<NativeBusinessDataRecord>,
    },
    SnapshotEnd {
        snapshot_id: String,
        cursor: String,
    },
    Upsert {
        cursor: String,
        record: NativeBusinessDataRecord,
        recovery: bool,
    },
    Remove {
        cursor: String,
        document_id: String,
        recovery: bool,
    },
    CaughtUp {
        cursor: String,
    },
    Reset {
        code: NativeBusinessDataErrorCode,
    },
    Revoked {
        message: String,
    },
    Command {
        state: NativeBusinessDataCommandState,
    },
    Error {
        code: NativeBusinessDataErrorCode,
        message: String,
        retryable: bool,
    },
}

fn deserialize_wire_u64<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<u64, D::Error> {
    let value = u64::deserialize(deserializer)?;
    if value > 9_007_199_254_740_991 {
        return Err(serde::de::Error::custom(
            "wire integer exceeds JavaScript safe range",
        ));
    }
    Ok(value)
}
