// Generated by ctox-sync/tools/generate-contracts.mjs. Do not edit.
// Fixture SHA-256: ec12f0b1360bc7e6eef4187f2a8cd13787c1253f7031dcd5d3bd9c885503bae2
use serde::{Deserialize, Serialize};
pub const CTOX_SYNC_AUTHORITY_PROTOCOL_VERSION: u32 = 5;
pub const CTOX_SYNC_IPC_PROTOCOL_VERSION: u32 = 1;
pub const CTOX_SYNC_IPC_MAX_FRAME_BYTES: u32 = 65536;
pub const CTOX_SYNC_IPC_DEADLINE_MILLIS: u32 = 10000;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum WorkspaceEntryKind {
    File,
    Symlink,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ExecutionPeer {
    pub identity: String,
    pub executor: bool,
    pub data_replica: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Copy)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SyncHostTiming {
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub heartbeat_ms: u64,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub election_min_ms: u64,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub election_max_ms: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SyncHostConfiguration {
    pub version: u32,
    pub scope_id: String,
    pub local: SyncHostMember,
    pub voters: std::collections::BTreeMap<u64, ExecutionPeer>,
    pub timing: SyncHostTiming,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SyncHostTransport {
    pub signaling_urls: Vec<String>,
    pub ice_servers: Vec<SyncHostIceServer>,
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SyncHostIceServer {
    pub urls: Vec<String>,
    pub username: String,
    pub credential: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkerMembership {
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub node_id: u64,
    pub identity: String,
    pub data_replica: bool,
    pub revoked: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SyncIpcRequest {
    pub version: u32,
    pub request_id: String,
    pub operation: SyncIpcOperation,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SyncIpcResponse {
    pub version: u32,
    pub request_id: String,
    pub result: SyncIpcResult,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ExecutionSpec {
    pub job_id: String,
    pub session_id: String,
    pub scope_id: String,
    pub harness: String,
    pub harness_version: String,
    pub model_route_id: String,
    pub gateway_account_id: String,
    pub model_id: String,
    pub required_capabilities: std::collections::BTreeSet<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ExecutionOwnership {
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub node_id: u64,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub generation: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CheckpointCopyReceipt {
    pub version: u32,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub node_id: u64,
    pub spec: ExecutionSpec,
    pub ownership: ExecutionOwnership,
    pub checkpoint_digest: String,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub sequence: u64,
    pub signature: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ArtifactRef {
    pub sha256: String,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub size_bytes: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct WorkspaceEntry {
    pub path: String,
    pub kind: WorkspaceEntryKind,
    pub artifact: ArtifactRef,
    pub executable: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SessionManifest {
    pub version: u32,
    pub scope_id: String,
    pub session_id: String,
    pub harness: String,
    pub harness_version: String,
    pub model_route_id: String,
    pub gateway_account_id: String,
    pub model_id: String,
    pub required_capabilities: std::collections::BTreeSet<String>,
    pub credential_references: std::collections::BTreeSet<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CheckpointManifest {
    pub version: u32,
    pub session: SessionManifest,
    #[serde(deserialize_with = "deserialize_wire_u64")]
    pub sequence: u64,
    pub base_commit: Option<String>,
    pub history: Vec<ArtifactRef>,
    pub attachments: Vec<ArtifactRef>,
    pub workspace: Vec<WorkspaceEntry>,
    pub provider_state: Vec<WorkspaceEntry>,
    pub pending_effects: Vec<PendingEffect>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PendingEffect {
    pub effect_id: String,
    pub idempotency_key: Option<String>,
    pub description: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct AppRelease {
    pub app_id: String,
    pub version: String,
    pub sha256: String,
    pub schema_hash: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct RuntimeManifest {
    pub version: u32,
    pub instance_id: String,
    pub shell_version: String,
    pub shell_sha256: String,
    pub sync_protocol_version: u32,
    pub schema_hash: String,
    pub native_version: String,
    pub apps: Vec<AppRelease>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum SyncHostMember {
    Voter {
        #[serde(deserialize_with = "deserialize_wire_u64")]
        node_id: u64,
    },
    Worker {
        member: WorkerMembership,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum AuthorityFailure {
    NotLeader {
        #[serde(default, deserialize_with = "deserialize_optional_wire_u64")]
        leader: Option<u64>,
    },
    Unavailable {
        reason: String,
    },
    Rejected {
        reason: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum SyncIpcOperation {
    Hello {},
    WorkerMembership {
        #[serde(deserialize_with = "deserialize_wire_u64")]
        node_id: u64,
    },
    AdmitWorker {
        worker: WorkerMembership,
    },
    RevokeWorker {
        #[serde(deserialize_with = "deserialize_wire_u64")]
        node_id: u64,
    },
    Create {
        spec: ExecutionSpec,
    },
    Validate {
        job_id: String,
        ownership: ExecutionOwnership,
    },
    ProtectCheckpoint {
        job_id: String,
        ownership: ExecutionOwnership,
        receipts: Vec<CheckpointCopyReceipt>,
    },
    TakeOver {
        job_id: String,
        expected: ExecutionOwnership,
        checkpoint_digest: String,
    },
    BeginEffect {
        job_id: String,
        ownership: ExecutionOwnership,
        effect_id: String,
    },
    CompleteEffect {
        job_id: String,
        ownership: ExecutionOwnership,
        effect_id: String,
    },
    Stop {
        job_id: String,
        ownership: ExecutionOwnership,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(
    tag = "type",
    rename_all = "camelCase",
    rename_all_fields = "camelCase",
    deny_unknown_fields
)]
pub enum SyncIpcResult {
    WorkerMembership {
        #[serde(deserialize_with = "deserialize_wire_u64")]
        node_id: u64,
        worker: Option<WorkerMembership>,
    },
    WorkerApplied {
        worker: WorkerMembership,
    },
    WorkerReplayed {
        worker: WorkerMembership,
    },
    Ready {
        #[serde(deserialize_with = "deserialize_wire_u64")]
        node_id: u64,
        scope_id: String,
        protocol_version: u32,
    },
    Authorized {
        spec: ExecutionSpec,
        ownership: ExecutionOwnership,
    },
    Applied {
        spec: ExecutionSpec,
        ownership: ExecutionOwnership,
    },
    Replayed {
        spec: ExecutionSpec,
        ownership: ExecutionOwnership,
    },
    Rejected {
        reason: String,
    },
    Unavailable {
        reason: String,
    },
}

fn deserialize_wire_u64<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<u64, D::Error> {
    let value = u64::deserialize(deserializer)?;
    if value > 9_007_199_254_740_991 {
        return Err(serde::de::Error::custom(
            "wire integer exceeds JavaScript safe range",
        ));
    }
    Ok(value)
}

fn deserialize_optional_wire_u64<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<Option<u64>, D::Error> {
    let value = Option::<u64>::deserialize(deserializer)?;
    if value.is_some_and(|value| value > 9_007_199_254_740_991) {
        return Err(serde::de::Error::custom(
            "wire integer exceeds JavaScript safe range",
        ));
    }
    Ok(value)
}
