import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const moduleRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (rel) => readFileSync(resolve(moduleRoot, rel), 'utf8');

const manifest = JSON.parse(read('module.json'));
const registry = JSON.parse(read('../registry.json'));
const registryEntry = registry.modules.find((item) => item.id === 'cv-print-builder');

assert.equal(manifest.id, 'cv-print-builder');
assert.equal(manifest.entry, 'modules/cv-print-builder/index.html');
assert.equal(manifest.install_scope, 'starter');
assert.equal(manifest.default_installed, true);
assert.ok(manifest.collections.includes('documents'));
assert.ok(manifest.collections.includes('document_versions'));
assert.ok(manifest.collections.includes('desktop_files'));
assert.ok(manifest.collections.includes('business_commands'));
assert.ok(manifest.collections.includes('ctox_queue_tasks'));

assert.ok(registryEntry, 'registry entry exists');
assert.equal(registryEntry.entry, manifest.entry);
assert.equal(registryEntry.install_scope, manifest.install_scope);
assert.deepEqual(registryEntry.collections, manifest.collections);

const source = read('index.js');
const markup = read('index.html');
const sourceArray = (name) => {
  const marker = `const ${name} = [`;
  const start = source.indexOf(marker);
  assert.notEqual(start, -1, `${name} is declared`);
  const end = source.indexOf('];', start);
  assert.notEqual(end, -1, `${name} array is closed`);
  return source.slice(start + marker.length, end);
};
const requiredCollections = sourceArray('REQUIRED_COLLECTIONS');
const liveCollections = sourceArray('LIVE_COLLECTIONS');
assert.match(markup, /multiple\s+data-cv-upload/);
assert.match(markup, /data-cv-search/);
assert.match(markup, /data-cv-sort/);
assert.match(source, /label:\s*'Minimal'/);
assert.match(source, /label:\s*'Klassisch'/);
assert.match(source, /label:\s*'Modern'/);
assert.match(source, /async function importPdfs/);
assert.match(source, /title:\s*'Print freigeben'/);
assert.match(source, /phase:\s*'approved'/);
assert.match(source, /view_mode:\s*'print'/);
assert.match(source, /applyLiveWorkflowState/);
assert.match(source, /buildLiveStatusIndex/);
assert.match(source, /const commandId = `cmd_\$\{crypto\.randomUUID\(\)\}`/);
assert.match(source, /id:\s*commandId/);
assert.match(source, /command_type:\s*'business_os\.chat\.task'/);
assert.match(source, /type:\s*'business_os\.chat\.task'/);
assert.match(source, /task_status:\s*'queued'/);
assert.match(source, /ctx\.commandBus\.dispatch/);
assert.match(source, /Flow öffnen/);
assert.match(source, /record_snapshot:\s*parserRecordSnapshot\(item\)/);
assert.doesNotMatch(source, /attachments:\s*\[/);
assert.doesNotMatch(source, /async function insertBusinessCommand/);
assert.match(source, /sync_collections:\s*\[/);
assert.match(source, /'desktop_file_chunks'/);
assert.doesNotMatch(requiredCollections, /'desktop_file_chunks'/);
assert.doesNotMatch(liveCollections, /'desktop_file_chunks'/);
assert.match(source, /'business_chats'/);
assert.match(source, /'ctox_queue_tasks'/);
assert.match(source, /data-cv-open-task/);
assert.match(source, /skill:\s*'ctox-cv-print-parser'/);
assert.match(source, /command_type:\s*'ctox\.cv_print\.apply_parse'/);
assert.match(source, /const taskInstruction = buildParserTaskInstruction\(item\)/);
assert.match(source, /instruction:\s*taskInstruction/);
assert.doesNotMatch(source, /instruction:\s*prompt,\s*\n\s*prompt,/);
assert.match(source, /Keine Tools, keine Shell/);
assert.match(source, /function renderPrintPane/);
assert.match(source, /function renderPrintSheet/);
assert.match(source, /reference:\s*'NinjaWorkflowTool_Extension\/find-job-for-candidate qualification profile'/);
assert.match(source, /expected_model_schema:\s*'ctox\.cv_print_profile\.v1'/);
assert.match(source, /QUALIFIKATIONSPROFIL/);
assert.match(source, /METHODEN- \/ SYSTEMKOMPETENZ \/ SPRACHKENNTNISSE/);
assert.match(source, /renderFieldEditor/);
assert.match(source, /data-cv-field-editor/);
assert.match(source, /cv\.experience: Array mit \{job_title,employer,location,start_date,end_date,job_description\[\]\}/);
assert.match(source, /cv\.education: Array mit \{degree,institution,major,specialization,location,start_date,end_date,details\[\]\}/);
assert.match(source, /cv\.skills: Objekt mit Gruppen/);
assert.doesNotMatch(source, /Limits: max\./);
assert.match(source, /importPdf\(state, file, \{ refresh: false, select: false \}\)/);
assert.match(source, /return \{ documentId, fileId \}/);
assert.match(source, /CONTENT_HASH_SCHEME\s*=\s*'sha256-bytes-v1'/);
assert.match(source, /CHUNK_HASH_SCHEME\s*=\s*'sha256-base64-chunk-v1'/);
assert.match(source, /CHUNK_SIZE\s*=\s*16\s*\*\s*1024/);
assert.match(source, /chunk_hash:\s*chunkHash/);
assert.match(source, /id:\s*canonicalDesktopFileChunkId\(input\.fileId,\s*input\.generationId,\s*idx\)/);
assert.match(source, /function canonicalDesktopFileChunkId\(fileId,\s*generationId,\s*idx\)/);
assert.match(source, /readStoredFileFromDemandChunks/);
assert.match(source, /readStoredFileFromChunks/);
assert.doesNotMatch(source, /findAll\(state\.ctx,\s*'desktop_file_chunks'\)/);
assert.match(source, /ensureParseSourceReady\(state,\s*item\)/);
assert.match(source, /ensureCanonicalDesktopFileChunks/);
assert.match(source, /readDesktopFileForCanonicalRepair/);
assert.match(source, /fetchDesktopFileChunks\(ctx,\s*fileId,\s*generationId\)/);
assert.match(source, /flushFileCollectionsForDispatch/);
assert.match(source, /const blob = await readDesktopFileForCanonicalRepair\(ctx,\s*fileId,\s*generationId,\s*contentHash\)/);
assert.match(source, /new Uint8Array\(await blob\.arrayBuffer\(\)\)/);
assert.match(source, /const base64 = uint8ToBase64\(bytes\)/);
assert.match(source, /Array\.from\(\{ length: total \}/);
assert.doesNotMatch(source, /String\(chunk\.bytesBase64 \?\? chunk\.bytes_base64 \?\? ''\)/);
assert.match(source, /source_prepare:\s*sourcePrepare/);
assert.match(source, /source_prepare_ready:\s*sourcePrepare\.ready/);
assert.match(source, /timeoutAfter\(12000/);
assert.match(source, /pushToRemotePeers/);
assert.match(source, /DEMAND_ONLY_SYNC_COLLECTIONS/);
assert.match(source, /sync\.leaseCollection\(collection,\s*reason\)/);
assert.match(source, /releaseSyncLeases/);
assert.match(source, /bulkUpsert\(docs\)/);
assert.doesNotMatch(source, /ctx\.sync\.startCollection\('desktop_file_chunks'\)/);

console.log('cv-print-builder module contract OK');
