//! Embedded PTX blobs compiled from `vendor/ggml-cuda/*.cu` by
//! `build.rs`.
//!
//! `build.rs` writes one `<stem>.ptx` per listed op into `$OUT_DIR`,
//! and this module pulls each into the final binary via
//! `include_str!`. Runtime code loads the blob with
//! `cuModuleLoadData` once per process (see [`load_module`]) and
//! looks up each mangled kernel name with `cuModuleGetFunction`.
//!
//! Keep the list in sync with `build.rs::CUDA_PORT_PTX_MODULES`.

use std::ffi::CString;

use super::driver::{
    cuGetErrorString, cuModuleGetFunction, cuModuleLoadData, CUDA_SUCCESS, CUfunction, CUmodule,
    CUresult,
};

/// `vendor/ggml-cuda/norm.cu` compiled to PTX at build time.
pub const NORM_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/norm.ptx"));

/// `vendor/ggml-cuda/unary.cu` compiled to PTX at build time.
pub const UNARY_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/unary.ptx"));

/// `vendor/ggml-cuda/scale.cu` compiled to PTX at build time.
pub const SCALE_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/scale.ptx"));

/// `vendor/ggml-cuda/fill.cu` compiled to PTX at build time.
pub const FILL_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/fill.ptx"));

/// `vendor/ggml-cuda/diag.cu` compiled to PTX at build time.
pub const DIAG_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/diag.ptx"));

/// `vendor/ggml-cuda/binbcast.cu` compiled to PTX at build time.
pub const BINBCAST_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/binbcast.ptx"));

/// `vendor/ggml-cuda/tri.cu` compiled to PTX at build time.
pub const TRI_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/tri.ptx"));

/// `vendor/ggml-cuda/pad.cu` compiled to PTX at build time.
pub const PAD_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/pad.ptx"));

/// `vendor/ggml-cuda/cumsum.cu` compiled to PTX at build time.
pub const CUMSUM_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/cumsum.ptx"));

/// `vendor/ggml-cuda/concat.cu` compiled to PTX at build time.
pub const CONCAT_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/concat.ptx"));

/// `vendor/ggml-cuda/cpy.cu` compiled to PTX at build time.
pub const CPY_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/cpy.ptx"));

/// `vendor/ggml-cuda/solve_tri.cu` compiled to PTX at build time.
pub const SOLVE_TRI_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/solve_tri.ptx"));

/// `vendor/ggml-cuda/rope.cu` compiled to PTX at build time.
pub const ROPE_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/rope.ptx"));

/// `vendor/ggml-cuda/softmax.cu` compiled to PTX at build time.
pub const SOFTMAX_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/softmax.ptx"));

/// `vendor/ggml-cuda/ssm-conv.cu` compiled to PTX at build time.
/// (Filename uses a dash upstream; the Rust module name uses the
/// snake-case `ssm_conv`.)
pub const SSM_CONV_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/ssm-conv.ptx"));

/// Auto-generated mangled-name table for `norm.ptx` — every `.entry`
/// symbol in the compiled PTX, each NUL-terminated for direct use
/// with `cuModuleGetFunction`. Regenerated by `build.rs`.
pub mod norm_entries {
    include!(concat!(env!("OUT_DIR"), "/norm_entries.rs"));
}

/// Auto-generated mangled-name table for `unary.ptx`.
pub mod unary_entries {
    include!(concat!(env!("OUT_DIR"), "/unary_entries.rs"));
}

/// Auto-generated mangled-name table for `scale.ptx`.
pub mod scale_entries {
    include!(concat!(env!("OUT_DIR"), "/scale_entries.rs"));
}

/// Auto-generated mangled-name table for `fill.ptx`.
pub mod fill_entries {
    include!(concat!(env!("OUT_DIR"), "/fill_entries.rs"));
}

/// Auto-generated mangled-name table for `diag.ptx`.
pub mod diag_entries {
    include!(concat!(env!("OUT_DIR"), "/diag_entries.rs"));
}

/// Auto-generated mangled-name table for `binbcast.ptx`.
pub mod binbcast_entries {
    include!(concat!(env!("OUT_DIR"), "/binbcast_entries.rs"));
}

/// Auto-generated mangled-name table for `tri.ptx`.
pub mod tri_entries {
    include!(concat!(env!("OUT_DIR"), "/tri_entries.rs"));
}

/// Auto-generated mangled-name table for `pad.ptx`.
pub mod pad_entries {
    include!(concat!(env!("OUT_DIR"), "/pad_entries.rs"));
}

/// Auto-generated mangled-name table for `cumsum.ptx`.
pub mod cumsum_entries {
    include!(concat!(env!("OUT_DIR"), "/cumsum_entries.rs"));
}

/// Auto-generated mangled-name table for `concat.ptx`.
pub mod concat_entries {
    include!(concat!(env!("OUT_DIR"), "/concat_entries.rs"));
}

/// Auto-generated mangled-name table for `cpy.ptx`.
pub mod cpy_entries {
    include!(concat!(env!("OUT_DIR"), "/cpy_entries.rs"));
}

/// Auto-generated mangled-name table for `solve_tri.ptx`.
pub mod solve_tri_entries {
    include!(concat!(env!("OUT_DIR"), "/solve_tri_entries.rs"));
}

/// Auto-generated mangled-name table for `rope.ptx`.
pub mod rope_entries {
    include!(concat!(env!("OUT_DIR"), "/rope_entries.rs"));
}

/// Auto-generated mangled-name table for `softmax.ptx`.
pub mod softmax_entries {
    include!(concat!(env!("OUT_DIR"), "/softmax_entries.rs"));
}

/// Auto-generated mangled-name table for `ssm-conv.ptx`.
pub mod ssm_conv_entries {
    include!(concat!(env!("OUT_DIR"), "/ssm-conv_entries.rs"));
}

/// Populated lookup for diagnostics.
pub fn all_embedded_ptx() -> &'static [(&'static str, &'static str)] {
    &[("norm", NORM_PTX), ("unary", UNARY_PTX), ("scale", SCALE_PTX)]
}

/// Find the single mangled kernel name in `entries` that matches
/// every substring in `needles`. Used by op dispatchers to locate
/// a specific kernel variant (e.g. `unary_op_kernel<op_silu, float>`)
/// without hard-coding the per-translation-unit-hash-dependent full
/// mangled name.
///
/// Returns `Err` if zero or more than one entry matches — both are
/// programmer errors that mean the needle set is too loose or the
/// kernel isn't in the PTX.
pub fn find_entry<'a>(
    entries: &'static [&'static [u8]],
    needles: &[&'a [u8]],
) -> Result<&'static [u8], String> {
    let matches: Vec<&'static [u8]> = entries
        .iter()
        .copied()
        .filter(|e| needles.iter().all(|n| slice_contains(e, n)))
        .collect();
    match matches.len() {
        1 => Ok(matches[0]),
        0 => Err(format!(
            "no PTX entry matches all of {:?}",
            needles.iter().map(|n| String::from_utf8_lossy(n)).collect::<Vec<_>>()
        )),
        _ => {
            let names: Vec<String> = matches
                .iter()
                .map(|e| String::from_utf8_lossy(e).to_string())
                .collect();
            Err(format!(
                "needles {:?} match {} entries: {:?}",
                needles.iter().map(|n| String::from_utf8_lossy(n)).collect::<Vec<_>>(),
                matches.len(),
                names
            ))
        }
    }
}

fn slice_contains(hay: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() {
        return true;
    }
    if needle.len() > hay.len() {
        return false;
    }
    hay.windows(needle.len()).any(|w| w == needle)
}

/// Load a PTX blob into the current CUDA context.
///
/// The blob must be NUL-terminated when passed to
/// `cuModuleLoadData`. `include_str!` produces a `&str` without a
/// trailing NUL, so we wrap it with `CString::new` at load time.
pub fn load_module(ptx: &str) -> Result<CUmodule, String> {
    let cptx = CString::new(ptx.as_bytes())
        .map_err(|e| format!("PTX contains interior NUL: {e}"))?;
    let mut module = CUmodule(std::ptr::null_mut());
    let rc = unsafe { cuModuleLoadData(&mut module, cptx.as_ptr() as *const _) };
    check(rc, "cuModuleLoadData")?;
    if module.0.is_null() {
        return Err("cuModuleLoadData succeeded but returned a null module".into());
    }
    Ok(module)
}

/// Look up a kernel function by its mangled name.
/// Pass a NUL-terminated byte slice (constants like
/// [`super::ops::norm::MANGLED_RMS_NORM_F32_B256`] include the NUL).
pub fn get_function(module: CUmodule, mangled_name_with_nul: &[u8]) -> Result<CUfunction, String> {
    debug_assert!(
        mangled_name_with_nul.ends_with(b"\0"),
        "mangled name constants must be NUL-terminated"
    );
    let mut func = CUfunction(std::ptr::null_mut());
    let rc = unsafe {
        cuModuleGetFunction(
            &mut func,
            module,
            mangled_name_with_nul.as_ptr() as *const _,
        )
    };
    let name = std::str::from_utf8(&mangled_name_with_nul[..mangled_name_with_nul.len() - 1])
        .unwrap_or("<invalid utf8>");
    check(rc, &format!("cuModuleGetFunction({name})"))?;
    if func.0.is_null() {
        return Err(format!(
            "cuModuleGetFunction({name}) succeeded but returned null"
        ));
    }
    Ok(func)
}

fn check(rc: CUresult, what: &str) -> Result<(), String> {
    if rc == CUDA_SUCCESS {
        Ok(())
    } else {
        let mut raw: *const std::os::raw::c_char = std::ptr::null();
        let sub = unsafe { cuGetErrorString(rc, &mut raw) };
        let msg = if sub == CUDA_SUCCESS && !raw.is_null() {
            unsafe { std::ffi::CStr::from_ptr(raw) }
                .to_string_lossy()
                .into_owned()
        } else {
            format!("CUresult({rc})")
        };
        Err(format!("{what}: {msg}"))
    }
}
