import "./vendor/react-libs.js";
import {
  createDefaultUiPreferences,
  readUiPreferences,
  writeUiPreferences,
} from "./shared/ui-preferences.mjs";
import {
  REMOTE_COMPUTE_ROLLOUT_ENABLED,
  REMOTE_COMPUTE_SETTINGS_DEFAULTS,
  normalizeRemoteComputeSettings,
} from "./shared/remote_compute.mjs";

const __g =
  typeof globalThis !== "undefined"
    ? globalThis
    : typeof window !== "undefined"
      ? window
      : self;

var react = __g.react || { exports: {} };
var reactDom = __g.reactDom || { exports: {} };
var client = __g.client || {};
var hasRequiredReact;
var hasRequiredReactDom;
var hasRequiredClient;
var requireReact_production_min = __g.requireReact_production_min;
var requireReactDom_production_min = __g.requireReactDom_production_min;
var getDefaultExportFromCjs =
  __g.getDefaultExportFromCjs ||
  function getDefaultExportFromCjsLocal(module) {
    return module && module.__esModule ? module.default : module;
  };

var requireReact =
  typeof requireReact !== "undefined"
    ? requireReact
    : function requireReactLocal() {
        if (hasRequiredReact) return react.exports;
        hasRequiredReact = 1;
        react.exports = requireReact_production_min();
        return react.exports;
      };

function requireReactDom() {
  if (hasRequiredReactDom) return reactDom.exports;
  hasRequiredReactDom = 1;
  reactDom.exports = requireReactDom_production_min();
  return reactDom.exports;
}

function requireClient() {
  if (hasRequiredClient) return client;
  hasRequiredClient = 1;
  const module = requireReactDom();
  client.createRoot = module.createRoot;
  client.hydrateRoot = module.hydrateRoot;
  return client;
}

const clientExports = requireClient();
const reactExports = requireReact();
const React = getDefaultExportFromCjs(reactExports);
const h = React.createElement;

const craftStore = globalThis.SinepanelCraftStorage || null;
let craftSync = globalThis.SinepanelCraftSync || null;
let craftSyncLoadPromise = null;
let craftSyncLoadError = "";
const themeApi = globalThis.SinepanelAppTheme || null;
const configApi = globalThis.SinepanelModelConfig || null;
const DEFAULT_SYNC_SETTINGS = {
  displayName: "",
  signalingUrls: craftSync?.DEFAULT_SIGNALING_URL || "wss://api.metricspace.org/signal",
  token: "",
  tokenAutoGenerated: true,
  mode: "off",
  ...REMOTE_COMPUTE_SETTINGS_DEFAULTS,
};

const SECTION_DEFS = [
  { id: "general", label: "General" },
  { id: "providers", label: "Providers" },
  { id: "models", label: "Models" },
  { id: "share", label: "Share" },
];

const SECTION_ALIASES = {
  appearance: "general",
  general: "general",
  global: "general",
  theme: "general",
  themes: "general",
  models: "models",
  providers: "providers",
  share: "share",
};

const LEGACY_WORKSPACE_SECTION_ALIASES = {
  training: "training-data",
  "training-data": "training-data",
  dataset: "training-data",
  data: "training-data",
  navigator: "navigator",
  bundle: "navigator",
};

function getCraftSync() {
  craftSync = globalThis.SinepanelCraftSync || craftSync || null;
  return craftSync;
}

async function ensureCraftSyncLoaded() {
  const existing = getCraftSync();
  if (existing) {
    craftSyncLoadError = "";
    return existing;
  }
  if (craftSyncLoadPromise) return craftSyncLoadPromise;

  craftSyncLoadPromise = import("./shared/craft-sync.js")
    .then(() => {
      const loaded = getCraftSync();
      if (!loaded) {
        throw new Error("Craft sync runtime did not register on globalThis.");
      }
      craftSyncLoadError = "";
      return loaded;
    })
    .catch((error) => {
      craftSync = null;
      craftSyncLoadError =
        error instanceof Error ? error.message : String(error || "Craft sync could not be loaded.");
      console.warn("[options] craft sync bootstrap failed", error);
      return null;
    })
    .finally(() => {
      craftSyncLoadPromise = null;
    });

  return craftSyncLoadPromise;
}

function normalizeSectionId(value) {
  const candidate = String(value || "").trim().toLowerCase();
  return SECTION_ALIASES[candidate] || null;
}

function normalizeLegacyWorkspaceSection(value) {
  const candidate = String(value || "").trim().toLowerCase();
  return LEGACY_WORKSPACE_SECTION_ALIASES[candidate] || null;
}

function normalizeLegacyCraftTab(value) {
  const candidate = String(value || "").trim().toLowerCase();
  if (["tools", "browser-functions", "browser-capabilities", "capabilities"].includes(candidate)) {
    return "browser-functions";
  }
  if (["tool-scripts", "scripts"].includes(candidate)) return "tool-scripts";
  if (candidate === "skillset") return "skills";
  if (candidate === "model") return "model";
  if (candidate === "lineage") return "lineage";
  return "model";
}

function buildCraftPageUrl(craftId, tab = "model") {
  const baseUrl = globalThis.chrome?.runtime?.getURL
    ? globalThis.chrome.runtime.getURL("craft.html")
    : new URL("craft.html", globalThis.location.href).toString();
  const url = new URL(baseUrl);
  const normalizedCraftId = String(craftId || "").trim();
  const normalizedTab = String(tab || "model").trim() || "model";
  if (normalizedCraftId) {
    url.searchParams.set("craft", normalizedCraftId);
  }
  url.searchParams.set("tab", normalizedTab);
  url.hash = normalizedTab;
  return url.toString();
}

function readPageRoute() {
  try {
    const url = new URL(location.href);
    return {
      section:
      normalizeSectionId(url.searchParams.get("section")) ||
      normalizeSectionId(String(location.hash || "").replace(/^#/, "").split("/")[0]) ||
      "general",
    };
  } catch (_error) {
    return {
      section: "general",
    };
  }
}

function readRequestedSection() {
  return readPageRoute().section;
}

function writePageRoute(route = {}) {
  const url = new URL(location.href);
  const sectionId = normalizeSectionId(route.section) || "general";

  url.searchParams.set("section", sectionId);
  url.searchParams.delete("craft");
  url.searchParams.delete("bundleTab");
  url.hash = sectionId;
  history.replaceState(null, "", url.toString());
}

function normalizeSyncSettings(value) {
  const raw = value && typeof value === "object" ? value : {};
  return {
    ...DEFAULT_SYNC_SETTINGS,
    ...raw,
    ...normalizeRemoteComputeSettings(raw),
  };
}

async function ensureRemoteComputeOffscreen(settings = DEFAULT_SYNC_SETTINGS, reason = "options") {
  if (!REMOTE_COMPUTE_ROLLOUT_ENABLED) return null;
  const normalized = normalizeSyncSettings(settings);
  const shouldBootstrap =
    normalized.mode === "continuous" &&
    (normalized.computeOfferEnabled === true || normalized.remoteExecutionEnabled === true);
  if (!shouldBootstrap || !chrome?.runtime?.sendMessage) return null;
  return await new Promise((resolve) => {
    chrome.runtime.sendMessage(
      {
        type: "compute:ensure-offscreen",
        reason,
      },
      (response) => {
        resolve(response || null);
      },
    );
  });
}

function formatCount(value) {
  return new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 }).format(
    Math.max(0, Number(value) || 0),
  );
}

function formatTimestamp(value) {
  const text = String(value || "").trim();
  if (!text) return "—";
  const timestamp = new Date(text);
  if (Number.isNaN(timestamp.getTime())) return text;
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(timestamp);
}

function hasCustomSyncCode(settings = DEFAULT_SYNC_SETTINGS) {
  const token = String(settings?.token || "").trim();
  return Boolean(token) && settings?.tokenAutoGenerated !== true;
}

function getSyncPasswordHint(settings = DEFAULT_SYNC_SETTINGS) {
  return hasCustomSyncCode(settings)
    ? "Peers need the same signaling server and the same share code."
    : "A random private code keeps this install local-only until you replace it.";
}

function getSyncSharingGuide(settings = DEFAULT_SYNC_SETTINGS) {
  return hasCustomSyncCode(settings)
    ? "Use the same signaling server and share code on another machine to exchange published crafts."
    : "Replace the auto-generated private code with your own share code before you publish crafts to peers.";
}

function isRemoteSharedCraft(craft) {
  return craftStore?.isRemoteSharedCraft?.(craft) === true;
}

function isForkCraft(craft) {
  return craftStore?.isForkCraft?.(craft) === true;
}

function getCraftForkCount(craft, crafts = []) {
  return Math.max(0, Number(craftStore?.getLineageForkCount?.(craft, crafts) || 0));
}

function buildSyncStatusLine(snapshot, settings = DEFAULT_SYNC_SETTINGS, localCrafts = []) {
  const syncState = snapshot?.sync || snapshot || null;
  const passwordNote = hasCustomSyncCode(settings)
    ? "Custom share code is active. Shared crafts are visible only to peers using the same server and code."
    : "Auto private code is active. This install stays local-only until you replace it with your own share code.";

  if (!syncState) {
    return `${passwordNote} Share settings are not loaded yet.`;
  }
  if (syncState.lastError) {
    return `${passwordNote} Last sync error: ${syncState.lastError}`;
  }
  if (syncState.running && syncState.connection === "connected") {
    return `${passwordNote} Live sync is active with ${formatCount(syncState.transportPeerCount || 0)} live links and ${formatCount(syncState.remotePeerCount || 0)} visible peers.`;
  }
  if (syncState.running) {
    return `${passwordNote} Sync is running and waiting for peers. Right now there are ${formatCount(syncState.remotePeerCount || 0)} visible peers.`;
  }
  if (syncState.lastSyncedAt) {
    return `${passwordNote} Remote cache last refreshed ${formatTimestamp(syncState.lastSyncedAt)}. ${formatCount(syncState.publishedCount || localCrafts.filter((craft) => craft?.sharing?.enabled === true).length)} crafts are currently shared out.`;
  }
  return `${passwordNote} No sync has run yet.`;
}

function maskKeyState(provider) {
  return String(provider?.apiKey || "").trim() ? "API key saved" : "No API key";
}

function providerDraftFromRecord(provider) {
  return {
    ...provider,
    modelNamesText: Array.isArray(provider?.modelNames)
      ? provider.modelNames.join(", ")
      : "",
  };
}

function providerRecordFromDraft(draft) {
  return {
    ...draft,
    modelNames: configApi.normalizeModelNames(draft?.modelNamesText || draft?.modelNames || []),
  };
}

function providerHasChanges(provider, draft) {
  return (
    JSON.stringify(providerRecordFromDraft(draft)) !== JSON.stringify(provider)
  );
}

function getSlotModelOptions(providers, slotId, providerId, currentModelName) {
  const providerOptions = configApi
    .collectModelOptions(providers, slotId)
    .filter((option) => option.providerId === providerId);
  const currentModel = String(currentModelName || "").trim();

  if (!currentModel || providerOptions.some((option) => option.modelName === currentModel)) {
    return providerOptions.map((option) => ({
      modelName: option.modelName,
      label: option.modelName,
    }));
  }

  return [
    {
      modelName: currentModel,
      label: `${currentModel} (Current)`,
    },
    ...providerOptions.map((option) => ({
      modelName: option.modelName,
      label: option.modelName,
    })),
  ];
}

function getReasoningOptions() {
  return (configApi?.REASONING_EFFORT_VALUES || [""]).map((value) => ({
    value,
    label: value ? value : "Off",
  }));
}

function usePageRoute() {
  const [route, setRoute] = React.useState(readPageRoute());

  React.useEffect(() => {
    const handleLocationChange = () => {
      setRoute(readPageRoute());
    };
    window.addEventListener("hashchange", handleLocationChange);
    window.addEventListener("popstate", handleLocationChange);
    return () => {
      window.removeEventListener("hashchange", handleLocationChange);
      window.removeEventListener("popstate", handleLocationChange);
    };
  }, []);

  const updateRoute = React.useCallback((patch = {}) => {
    const current = readPageRoute();
    const nextRoute = {
      ...current,
      ...patch,
    };
    nextRoute.section = normalizeSectionId(nextRoute.section) || "general";
    writePageRoute(nextRoute);
    setRoute(readPageRoute());
  }, []);

  return [route, updateRoute];
}

function FieldRow({ label, note, children }) {
  return h("div", { className: "field-row" }, [
    h("div", { className: "field-copy", key: "copy" }, [
      h("div", { className: "field-label", key: "label" }, label),
      note ? h("div", { className: "field-note", key: "note" }, note) : null,
    ]),
    h("div", { className: "field-control", key: "control" }, children),
  ]);
}

function StatusPill({ tone = "muted", children }) {
  return h(
    "span",
    { className: `status-pill status-pill-${tone}` },
    children,
  );
}

function GeneralSection({ themeId, onThemeChange, configVersion }) {
  const themes = Array.isArray(themeApi?.THEMES) ? themeApi.THEMES : [];
  const activeTheme = themeApi?.getTheme?.(themeId) || themes[0] || null;
  const [summary, setSummary] = React.useState({
    loading: true,
    providerCount: 0,
    startupReady: false,
    missingCount: 0,
  });
  const [uiPreferences, setUiPreferences] = React.useState(createDefaultUiPreferences());
  const [uiPreferencesLoading, setUiPreferencesLoading] = React.useState(true);
  const [uiPreferencesSaving, setUiPreferencesSaving] = React.useState(false);
  const [uiPreferencesError, setUiPreferencesError] = React.useState("");

  React.useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const [providersResult, uiPreferencesResult] = await Promise.allSettled([
          configApi.readProviders(),
          readUiPreferences(craftSync),
        ]);
        const providers =
          providersResult.status === "fulfilled" ? providersResult.value : {};
        const slots = await configApi.readModelSlots(providers);
        const setup = configApi.getRequiredSetupStatus(slots, providers);
        if (!alive) return;
        setSummary({
          loading: false,
          providerCount: Object.keys(providers || {}).length,
          startupReady: setup.ready,
          missingCount: setup.missingCount,
        });
        setUiPreferences(
          uiPreferencesResult.status === "fulfilled"
            ? uiPreferencesResult.value
            : createDefaultUiPreferences(),
        );
        setUiPreferencesLoading(false);
        setUiPreferencesError("");
      } catch (_error) {
        if (!alive) return;
        setSummary({
          loading: false,
          providerCount: 0,
          startupReady: false,
          missingCount: 0,
        });
        setUiPreferences(createDefaultUiPreferences());
        setUiPreferencesLoading(false);
        setUiPreferencesError("");
      }
    })();
    return () => {
      alive = false;
    };
  }, [configVersion]);

  const handleDevModeToggle = React.useCallback(
    async (enabled) => {
      const previousPreferences = uiPreferences;
      const nextPreferences = {
        ...previousPreferences,
        showDevHeader: enabled === true,
      };
      setUiPreferences(nextPreferences);
      setUiPreferencesSaving(true);
      setUiPreferencesError("");
      try {
        const persistedPreferences = await writeUiPreferences(craftSync, nextPreferences);
        setUiPreferences(persistedPreferences);
      } catch (error) {
        setUiPreferences(previousPreferences);
        setUiPreferencesError(error instanceof Error ? error.message : "Dev mode could not be saved.");
      } finally {
        setUiPreferencesSaving(false);
      }
    },
    [uiPreferences],
  );

  return h("section", { className: "options-card" }, [
    h("div", { className: "section-header", key: "head" }, [
      h("div", { key: "copy" }, [
        h("div", { className: "section-eyebrow", key: "eyebrow" }, "Global"),
        h("h1", { className: "section-title", key: "title" }, "General"),
        h(
          "p",
          { className: "section-description", key: "description" },
          activeTheme
            ? `Global settings for the extension. The current theme is ${activeTheme.title}.`
            : "Global settings for the extension.",
        ),
      ]),
    ]),
    h("div", { className: "editor-pill-row", key: "summary" }, [
      h(StatusPill, { tone: "muted", key: "theme" }, activeTheme ? activeTheme.title : "Theme"),
      h(
        StatusPill,
        { tone: summary.loading ? "muted" : "ready", key: "providers" },
        summary.loading ? "Loading providers..." : `${summary.providerCount} providers`,
      ),
      h(
        StatusPill,
        { tone: summary.loading ? "muted" : summary.startupReady ? "ready" : "warning", key: "setup" },
        summary.loading
          ? "Checking startup"
          : summary.startupReady
            ? "Startup ready"
            : `${summary.missingCount} setup items missing`,
      ),
      h(
        StatusPill,
        {
          tone: uiPreferences.showDevHeader ? "warning" : "muted",
          key: "dev-mode",
        },
        uiPreferences.showDevHeader ? "Dev mode on" : "Dev mode off",
      ),
    ]),
    h(
      "div",
      { className: "theme-grid", key: "grid" },
      themes.map((theme) =>
        h(
          "button",
          {
            className: `theme-chip ${theme.id === themeId ? "theme-chip-active" : ""}`,
            type: "button",
            onClick: () => onThemeChange(theme.id),
            key: theme.id,
          },
          [
            h("span", { className: "theme-chip-label", key: "label" }, theme.label),
            h("span", { className: "theme-chip-meta", key: "note" }, theme.shortNote || ""),
            h("span", { className: "theme-chip-description", key: "description" }, theme.description),
          ],
        ),
      ),
    ),
    h(
      FieldRow,
      {
        label: "Dev mode",
        note:
          "Show the sidepanel test header with inference, vision, self-use, agentic, training, workspace, and tool smoke buttons.",
        key: "dev-mode-toggle",
      },
      h("label", { className: "toggle-row" }, [
        h("input", {
          type: "checkbox",
          checked: uiPreferences.showDevHeader === true,
          disabled: uiPreferencesLoading || uiPreferencesSaving,
          onChange: (event) => void handleDevModeToggle(event.target.checked),
          key: "input",
        }),
        h(
          "span",
          { key: "text" },
          uiPreferencesLoading
            ? "Loading..."
            : uiPreferencesSaving
              ? "Saving..."
              : uiPreferences.showDevHeader
                ? "Show test header"
                : "Hide test header",
        ),
      ]),
    ),
    uiPreferencesError
      ? h("div", { className: "status-message status-message-error", key: "dev-mode-error" }, uiPreferencesError)
      : null,
  ]);
}

function ShareCraftRow({
  craft,
  pills = [],
  meta = "",
  summary = "",
  actionLabel,
  actionTone = "ghost",
  actionDisabled = false,
  actionBusy = false,
  onAction,
}) {
  return h("article", { className: "share-row" }, [
    h("div", { className: "share-row-copy", key: "copy" }, [
      h("div", { className: "share-row-head", key: "head" }, [
        h("h2", { className: "share-row-title", key: "title" }, craft?.name || "Untitled craft"),
        h(
          "div",
          { className: "editor-pill-row", key: "pills" },
          pills.map((pill, index) =>
            h(StatusPill, { tone: pill.tone || "muted", key: `${pill.label}:${index}` }, pill.label),
          ),
        ),
      ]),
      summary
        ? h("p", { className: "share-row-summary", key: "summary" }, summary)
        : null,
      meta
        ? h("div", { className: "share-row-meta", key: "meta" }, meta)
        : null,
    ]),
    h("div", { className: "share-row-actions", key: "actions" }, [
      h(
        "button",
        {
          className: `options-button ${
            actionTone === "danger" ? "options-button-danger" : "options-button-ghost"
          }`,
          type: "button",
          disabled: actionDisabled || actionBusy,
          onClick: onAction,
          key: "action",
        },
        actionBusy ? "Working..." : actionLabel,
      ),
    ]),
  ]);
}

function ShareSection() {
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState("");
  const [busyAction, setBusyAction] = React.useState("");
  const [localCrafts, setLocalCrafts] = React.useState([]);
  const [crafts, setCrafts] = React.useState([]);
  const [syncSettings, setSyncSettings] = React.useState(DEFAULT_SYNC_SETTINGS);
  const [syncDraft, setSyncDraft] = React.useState(DEFAULT_SYNC_SETTINGS);
  const [syncSnapshot, setSyncSnapshot] = React.useState(getCraftSync()?.getState?.() || null);

  const loadShareState = React.useCallback(async ({ showLoading = false } = {}) => {
    if (showLoading) setLoading(true);
    try {
      await ensureCraftSyncLoaded();
      const syncApi = getCraftSync();
      const [nextLocalCrafts, nextCrafts, nextSyncSettings] = await Promise.all([
        craftStore?.readLocalCrafts?.() || [],
        craftStore?.readCrafts?.() || [],
        syncApi?.readSettings?.() || DEFAULT_SYNC_SETTINGS,
      ]);
      const normalizedSettings = normalizeSyncSettings(nextSyncSettings);
      setLocalCrafts(Array.isArray(nextLocalCrafts) ? nextLocalCrafts : []);
      setCrafts(Array.isArray(nextCrafts) ? nextCrafts : []);
      setSyncSettings(normalizedSettings);
      setSyncDraft(normalizedSettings);
      setSyncSnapshot(syncApi?.getState?.() || null);
      await ensureRemoteComputeOffscreen(normalizedSettings, "options-load");
      setError(craftSyncLoadError || "");
    } catch (loadError) {
      setError(
        loadError instanceof Error
          ? loadError.message
          : String(loadError || "Share settings could not be loaded."),
      );
    } finally {
      if (showLoading) setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    let cancelled = false;

    (async () => {
      try {
        const syncApi = await ensureCraftSyncLoaded();
        await syncApi?.ensureStartedFromSettings?.({ pageName: "Options" });
      } catch (startupError) {
        if (!cancelled) {
          setError(
            startupError instanceof Error
              ? startupError.message
              : String(startupError || "Sharing sync could not be started."),
          );
        }
      }
      if (cancelled) return;
      await loadShareState({ showLoading: true });
    })();

    return () => {
      cancelled = true;
    };
  }, [loadShareState]);

  React.useEffect(() => {
    let active = true;
    let unsubscribe = null;

    void (async () => {
      const syncApi = await ensureCraftSyncLoaded();
      if (!active || typeof syncApi?.subscribe !== "function") return;
      unsubscribe = syncApi.subscribe((snapshot) => {
        setSyncSnapshot(snapshot || null);
        const type = String(snapshot?.detail?.type || "").trim();
        if (["compute-workers", "settings-updated", "webrtc-connect", "webrtc-disconnect", "transport-peers"].includes(type)) {
          void loadShareState();
        }
      });
    })();

    return () => {
      active = false;
      try {
        unsubscribe?.();
      } catch (_error) {}
    };
  }, [loadShareState]);

  const runShareAction = React.useCallback(
    async (actionId, task) => {
      setBusyAction(actionId);
      setError("");
      try {
        await task();
        await loadShareState();
      } catch (actionError) {
        setError(
          actionError instanceof Error
            ? actionError.message
            : String(actionError || "The share action failed."),
        );
      } finally {
        setBusyAction("");
      }
    },
    [loadShareState],
  );

  const draftHasChanges =
    JSON.stringify(syncDraft) !== JSON.stringify(syncSettings);
  const snapshot = syncSnapshot?.sync || null;
  const remoteCrafts = crafts.filter((craft) => isRemoteSharedCraft(craft));
  const sharedCount = localCrafts.filter((craft) => craft?.sharing?.enabled === true).length;
  const isLive = snapshot?.requestedMode === "continuous" && snapshot?.running;
  const saveSyncDraft = React.useCallback(async () => {
    const nextSettings = normalizeSyncSettings(syncDraft);
    await runShareAction("save-sync", async () => {
      await getCraftSync()?.updateSettings?.(nextSettings);
    });
  }, [runShareAction, syncDraft]);

  const syncNow = React.useCallback(async () => {
    const nextSettings = normalizeSyncSettings(syncDraft);
    await runShareAction("sync-now", async () => {
      await getCraftSync()?.updateSettings?.(nextSettings);
      await getCraftSync()?.syncNow?.({ pageName: "Options" });
    });
  }, [runShareAction, syncDraft]);

  const startLiveSync = React.useCallback(async () => {
    const nextSettings = normalizeSyncSettings({
      ...syncDraft,
      mode: "continuous",
    });
    setSyncDraft(nextSettings);
    await runShareAction("start-live-sync", async () => {
      await getCraftSync()?.updateSettings?.(nextSettings);
      await getCraftSync()?.ensureStartedFromSettings?.({ pageName: "Options" });
    });
  }, [runShareAction, syncDraft]);

  const stopLiveSync = React.useCallback(async () => {
    const nextSettings = normalizeSyncSettings({
      ...syncDraft,
      mode: "off",
    });
    setSyncDraft(nextSettings);
    await runShareAction("stop-live-sync", async () => {
      await getCraftSync()?.updateSettings?.(nextSettings);
    });
  }, [runShareAction, syncDraft]);

  const randomizeSyncCode = React.useCallback(async () => {
    const nextSettings = normalizeSyncSettings({
      ...syncDraft,
      token: getCraftSync()?.generateRandomToken?.() || "",
      tokenAutoGenerated: true,
    });
    setSyncDraft(nextSettings);
    await runShareAction("randomize-sync-code", async () => {
      await getCraftSync()?.updateSettings?.(nextSettings);
    });
  }, [runShareAction, syncDraft]);

  const toggleCraftShare = React.useCallback(
    async (craftId) => {
      const targetCraft = localCrafts.find((craft) => craft.id === craftId) || null;
      if (!targetCraft) return;
      if (targetCraft?.sharing?.enabled !== true && !hasCustomSyncCode(syncDraft)) {
        setError("Set your own share code first, then share a craft.");
        return;
      }

      await runShareAction(`share:${craftId}`, async () => {
        const nextLocalCrafts = localCrafts.map((craft) => {
          if (craft.id !== craftId) return craft;
          const now = new Date().toISOString();
          return craftStore.normalizeCraft({
            ...craft,
            updatedAt: now,
            sharing: {
              enabled: craft?.sharing?.enabled !== true,
              publishedAt: craft?.sharing?.enabled === true ? "" : now,
            },
          });
        });
        await craftStore?.writeCrafts?.(nextLocalCrafts);
      });
    },
    [localCrafts, runShareAction, syncDraft],
  );

  const forkRemoteCraft = React.useCallback(
    async (craftId) => {
      const targetCraft = crafts.find((craft) => craft.id === craftId) || null;
      if (!targetCraft) return;
      const fork = craftStore?.createForkFromCraft?.(targetCraft, localCrafts);
      if (!fork) return;

      await runShareAction(`fork:${craftId}`, async () => {
        await craftStore?.writeCrafts?.([...localCrafts, fork]);
        await getCraftSync()?.materializeBundleArtifactsForCraft?.(targetCraft, fork.id);
      });
    },
    [crafts, localCrafts, runShareAction],
  );

  return h("section", { className: "options-card" }, [
    h("div", { className: "section-header", key: "header" }, [
      h("div", { key: "copy" }, [
        h("div", { className: "section-eyebrow", key: "eyebrow" }, "Peer Sync"),
        h("h1", { className: "section-title", key: "title" }, "Share"),
        h(
          "p",
          { className: "section-description", key: "description" },
          "P2P session setup, publishing, remote craft intake, and bundle distribution live in the same React settings shell.",
        ),
      ]),
      h("div", { className: "editor-pill-row", key: "pills" }, [
        h(StatusPill, { tone: isLive ? "ready" : "muted", key: "live" }, isLive ? "Live sync" : "Manual sync"),
        h(StatusPill, { tone: "muted", key: "links" }, `${formatCount(snapshot?.transportPeerCount || 0)} live links`),
        h(StatusPill, { tone: "muted", key: "peers" }, `${formatCount(snapshot?.remotePeerCount || 0)} visible peers`),
        h(StatusPill, { tone: sharedCount ? "ready" : "muted", key: "shared" }, `${formatCount(sharedCount)} shared out`),
        h(StatusPill, { tone: remoteCrafts.length ? "warning" : "muted", key: "remote" }, `${formatCount(remoteCrafts.length)} remote crafts`),
      ]),
    ]),
    loading
      ? h("div", { className: "status-message", key: "loading" }, "Loading share settings...")
      : null,
    error
      ? h("div", { className: "status-message status-message-error", key: "error" }, error)
      : null,
    h("div", { className: "setup-banner", key: "guide" }, [
      h("strong", { key: "title" }, "Share only with trusted peers."),
      h("span", { key: "body" }, getSyncSharingGuide(syncDraft)),
    ]),
    h("div", { className: "editor-list share-section-list", key: "list" }, [
      h("article", { className: "editor-card", key: "connection" }, [
        h("div", { className: "editor-header", key: "header" }, [
          h("div", { key: "copy" }, [
            h("h2", { className: "editor-title", key: "title" }, "Connection"),
            h("div", { className: "editor-subtitle", key: "subtitle" }, "Signaling and share code"),
          ]),
          h("div", { className: "editor-pill-row", key: "pills" }, [
            h(StatusPill, { tone: hasCustomSyncCode(syncDraft) ? "ready" : "warning", key: "code" }, hasCustomSyncCode(syncDraft) ? "Custom code" : "Auto private code"),
            h(StatusPill, { tone: "muted", key: "mode" }, syncDraft.mode || "off"),
          ]),
        ]),
        h(FieldRow, { label: "Display name", key: "displayName" }, h("input", {
          className: "options-input",
          value: syncDraft.displayName || "",
          onChange: (event) => setSyncDraft((previous) => ({
            ...previous,
            displayName: event.target.value,
          })),
          spellCheck: false,
          placeholder: "Michael",
        })),
        h(FieldRow, { label: "Signaling server", note: "Both sides need the same server URL.", key: "signalingUrls" }, h("textarea", {
          className: "options-input options-textarea",
          value: syncDraft.signalingUrls || "",
          onChange: (event) => setSyncDraft((previous) => ({
            ...previous,
            signalingUrls: event.target.value,
          })),
          spellCheck: false,
        })),
        h(FieldRow, { label: "Share code", note: getSyncPasswordHint(syncDraft), key: "token" }, h("input", {
          className: "options-input",
          type: "password",
          value: syncDraft.token || "",
          onChange: (event) => setSyncDraft((previous) => ({
            ...previous,
            token: event.target.value,
            tokenAutoGenerated: false,
          })),
          spellCheck: false,
        })),
        h(FieldRow, { label: "Mode", key: "mode" }, h(
          "select",
          {
            className: "options-select",
            value: syncDraft.mode || "off",
            onChange: (event) => setSyncDraft((previous) => ({
              ...previous,
              mode: event.target.value,
            })),
          },
          [
            h("option", { value: "off", key: "off" }, "Off"),
            h("option", { value: "manual", key: "manual" }, "One-shot sync"),
            h("option", { value: "continuous", key: "continuous" }, "Continuous sync"),
          ],
        )),
        h("div", { className: "action-row", key: "actions" }, [
          h("button", {
            className: "options-button",
            type: "button",
            disabled: busyAction !== "" || !draftHasChanges,
            onClick: () => void saveSyncDraft(),
            key: "save",
          }, busyAction === "save-sync" ? "Saving..." : "Save connection"),
          h("button", {
            className: "options-button options-button-ghost",
            type: "button",
            disabled: busyAction !== "",
            onClick: () => void syncNow(),
            key: "syncNow",
          }, busyAction === "sync-now" ? "Syncing..." : "Sync once"),
          h("button", {
            className: `options-button ${isLive ? "options-button-danger" : "options-button-ghost"}`,
            type: "button",
            disabled: busyAction !== "",
            onClick: () => void (isLive ? stopLiveSync() : startLiveSync()),
            key: "live",
          }, busyAction === "start-live-sync" || busyAction === "stop-live-sync" ? "Working..." : isLive ? "Stop live sync" : "Start live sync"),
          h("button", {
            className: "options-button options-button-ghost",
            type: "button",
            disabled: busyAction !== "",
            onClick: () => void randomizeSyncCode(),
            key: "randomize",
          }, busyAction === "randomize-sync-code" ? "Randomizing..." : "Randomize code"),
        ]),
        h("div", { className: "status-line", key: "status" }, [
          h("span", { className: "status-line-primary", key: "primary" }, "Sync status"),
          h("span", { className: "status-line-secondary", key: "secondary" }, buildSyncStatusLine(syncSnapshot, syncSettings, localCrafts)),
        ]),
      ]),
      REMOTE_COMPUTE_ROLLOUT_ENABLED
        ? h("article", { className: "editor-card", key: "compute-disabled" }, [
            h("div", { className: "editor-header", key: "header" }, [
              h("div", { key: "copy" }, [
                h("h2", { className: "editor-title", key: "title" }, "Remote compute"),
                h("div", { className: "editor-subtitle", key: "subtitle" }, "This rollout is currently disabled."),
              ]),
            ]),
          ])
        : null,
      h("article", { className: "editor-card", key: "published" }, [
        h("div", { className: "editor-header", key: "header" }, [
          h("div", { key: "copy" }, [
            h("h2", { className: "editor-title", key: "title" }, "Published crafts"),
            h("div", { className: "editor-subtitle", key: "subtitle" }, "Local capabilities you can share"),
          ]),
          h(StatusPill, { tone: sharedCount ? "ready" : "muted", key: "count" }, `${formatCount(sharedCount)} shared`),
        ]),
        localCrafts.length
          ? h(
              "div",
              { className: "share-list", key: "list" },
              localCrafts.map((craft) => {
                const isShared = craft?.sharing?.enabled === true;
                const forkCount = getCraftForkCount(craft, crafts);
                const pills = [
                  { label: isShared ? "Shared" : "Local", tone: isShared ? "ready" : "muted" },
                  { label: isForkCraft(craft) ? "Fork" : "Origin", tone: isForkCraft(craft) ? "warning" : "muted" },
                  { label: `${formatCount(forkCount)} forks`, tone: "muted" },
                ];
                const meta = [
                  isShared
                    ? `Published ${formatTimestamp(craft?.sharing?.publishedAt || craft.updatedAt || "")}`
                    : hasCustomSyncCode(syncDraft)
                      ? "Visible only on this machine until you share it"
                      : "Set your own share code before publishing",
                  formatTimestamp(craft.updatedAt || craft.createdAt || ""),
                ].filter(Boolean).join(" · ");
                return h(ShareCraftRow, {
                  craft,
                  pills,
                  meta,
                  summary: craft.summary || "",
                  actionLabel: isShared ? "Unshare" : "Share",
                  actionTone: isShared ? "danger" : "ghost",
                  actionDisabled: !isShared && !hasCustomSyncCode(syncDraft),
                  actionBusy: busyAction === `share:${craft.id}`,
                  onAction: () => void toggleCraftShare(craft.id),
                  key: craft.id,
                });
              }),
            )
          : h("div", { className: "status-message", key: "empty" }, "Create a local craft first, then publish it to peers."),
      ]),
      h("article", { className: "editor-card", key: "remote" }, [
        h("div", { className: "editor-header", key: "header" }, [
          h("div", { key: "copy" }, [
            h("h2", { className: "editor-title", key: "title" }, "Remote crafts"),
            h("div", { className: "editor-subtitle", key: "subtitle" }, "Mirrors visible in the current peer session"),
          ]),
          h(StatusPill, { tone: remoteCrafts.length ? "warning" : "muted", key: "count" }, `${formatCount(remoteCrafts.length)} cached`),
        ]),
        remoteCrafts.length
          ? h(
              "div",
              { className: "share-list", key: "list" },
              remoteCrafts.map((craft) => {
                const owner = String(craft?.sync?.ownerName || craft?.sync?.ownerDeviceId || "remote peer").trim();
                const pills = [
                  { label: "Mirror", tone: "warning" },
                  { label: isForkCraft(craft) ? "Fork mirror" : "Origin mirror", tone: "muted" },
                  { label: `${formatCount(getCraftForkCount(craft, crafts))} forks`, tone: "muted" },
                ];
                const meta = [
                  owner,
                  craft?.sync?.mode === "live" ? "live mirror" : "cached mirror",
                  formatTimestamp(craft?.sync?.syncedAt || craft.updatedAt || ""),
                ].filter(Boolean).join(" · ");
                return h(ShareCraftRow, {
                  craft,
                  pills,
                  meta,
                  summary: craft.summary || "",
                  actionLabel: "Fork locally",
                  actionTone: "ghost",
                  actionBusy: busyAction === `fork:${craft.id}`,
                  onAction: () => void forkRemoteCraft(craft.id),
                  key: craft.id,
                });
              }),
            )
          : h("div", { className: "status-message", key: "empty" }, "No remote crafts yet. Use the same signaling server and share code on another device, then run a sync."),
      ]),
    ]),
  ]);
}

function ProviderEditor({
  provider,
  draft,
  isFocused,
  isSaving,
  saveError,
  onChange,
  onSave,
  onDelete,
}) {
  const isLocal = provider.type === "local_qwen";
  const isCustom = provider.type === "custom_openai";
  const hasChanges = providerHasChanges(provider, draft);

  return h("article", { className: `editor-card ${isFocused ? "editor-card-focused" : ""}` }, [
    h("div", { className: "editor-header", key: "header" }, [
      h("div", { key: "copy" }, [
        h("h2", { className: "editor-title", key: "title" }, draft.name || provider.id),
        h("div", { className: "editor-subtitle", key: "subtitle" }, draft.type),
      ]),
      h("div", { className: "editor-pill-row", key: "pills" }, [
        h(StatusPill, { tone: draft.enabled ? "ready" : "muted", key: "enabled" }, draft.enabled ? "Enabled" : "Disabled"),
        h(StatusPill, { tone: String(draft.apiKey || "").trim() ? "ready" : "warning", key: "key" }, maskKeyState(draft)),
        h(StatusPill, { tone: "muted", key: "models" }, `${configApi.normalizeModelNames(draft.modelNamesText || []).length} models`),
      ]),
    ]),
    h(FieldRow, { label: "Enabled", note: isLocal ? "Local runtime stays enabled." : "Disable providers you do not want in role pickers.", key: "enabled" }, h("label", { className: "toggle-row" }, [
      h("input", {
        type: "checkbox",
        checked: draft.enabled === true,
        disabled: isLocal,
        onChange: (event) => onChange({ ...draft, enabled: event.target.checked }),
        key: "input",
      }),
      h("span", { key: "text" }, draft.enabled ? "On" : "Off"),
    ])),
    h(FieldRow, { label: "Name", key: "name" }, h("input", {
      className: "options-input",
      value: draft.name || "",
      onChange: (event) => onChange({ ...draft, name: event.target.value }),
      spellCheck: false,
    })),
    isLocal
      ? null
      : h(FieldRow, { label: "Base URL", key: "baseUrl" }, h("input", {
          className: "options-input",
          value: draft.baseUrl || "",
          onChange: (event) => onChange({ ...draft, baseUrl: event.target.value }),
          spellCheck: false,
          placeholder: "https://api.example.com/v1",
        })),
    isLocal
      ? null
      : h(FieldRow, { label: "API Key", key: "apiKey" }, h("input", {
          className: "options-input",
          type: "password",
          value: draft.apiKey || "",
          onChange: (event) => onChange({ ...draft, apiKey: event.target.value }),
          spellCheck: false,
          placeholder: "sk-...",
        })),
    h(
      FieldRow,
      {
        label: "Models",
        note: "Comma-separated list. These names populate the role model selectors.",
        key: "models",
      },
      h("input", {
        className: "options-input",
        value: draft.modelNamesText || "",
        onChange: (event) => onChange({ ...draft, modelNamesText: event.target.value }),
        spellCheck: false,
        placeholder: "gpt-5-mini, gpt-5.4, gpt-4.1",
      }),
    ),
    saveError
      ? h("div", { className: "status-message status-message-error", key: "error" }, saveError)
      : null,
    h("div", { className: "action-row", key: "actions" }, [
      h(
        "button",
        {
          className: "options-button",
          type: "button",
          disabled: isSaving || !hasChanges,
          onClick: onSave,
          key: "save",
        },
        isSaving ? "Saving..." : "Save",
      ),
      isCustom
        ? h(
            "button",
            {
              className: "options-button options-button-danger",
              type: "button",
              disabled: isSaving,
              onClick: onDelete,
              key: "delete",
            },
            "Delete",
          )
        : null,
    ]),
  ]);
}

function ProvidersSection({ configVersion, focusedProviderId }) {
  const [providers, setProviders] = React.useState({});
  const [drafts, setDrafts] = React.useState({});
  const [loading, setLoading] = React.useState(true);
  const [savingId, setSavingId] = React.useState("");
  const [saveErrors, setSaveErrors] = React.useState({});

  const loadProviders = React.useCallback(async () => {
    setLoading(true);
    try {
      const nextProviders = await configApi.readProviders();
      const nextDrafts = {};
      for (const [providerId, provider] of Object.entries(nextProviders)) {
        nextDrafts[providerId] = providerDraftFromRecord(provider);
      }
      setProviders(nextProviders);
      setDrafts(nextDrafts);
      setSaveErrors({});
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    void loadProviders();
  }, [loadProviders, configVersion]);

  const orderedProviderIds = React.useMemo(
    () => configApi.orderProviderIds(providers),
    [providers],
  );

  const saveProvider = React.useCallback(
    async (providerId) => {
      const draft = drafts[providerId];
      if (!draft) return;
      setSavingId(providerId);
      setSaveErrors((previous) => ({ ...previous, [providerId]: "" }));
      try {
        const nextProviders = {
          ...providers,
          [providerId]: providerRecordFromDraft(draft),
        };
        const writtenProviders = await configApi.writeProviders(nextProviders);
        const normalizedSlots = await configApi.readModelSlots(writtenProviders);
        await configApi.writeModelSlots(normalizedSlots, writtenProviders);
        const nextDrafts = {};
        for (const [currentProviderId, currentProvider] of Object.entries(writtenProviders)) {
          nextDrafts[currentProviderId] = providerDraftFromRecord(currentProvider);
        }
        setProviders(writtenProviders);
        setDrafts(nextDrafts);
      } catch (error) {
        setSaveErrors((previous) => ({
          ...previous,
          [providerId]: error instanceof Error ? error.message : String(error || "Provider could not be saved."),
        }));
      } finally {
        setSavingId("");
      }
    },
    [drafts, providers],
  );

  const deleteProvider = React.useCallback(
    async (providerId) => {
      setSavingId(providerId);
      setSaveErrors((previous) => ({ ...previous, [providerId]: "" }));
      try {
        const nextProviders = { ...providers };
        delete nextProviders[providerId];
        const writtenProviders = await configApi.writeProviders(nextProviders);
        const normalizedSlots = await configApi.readModelSlots(writtenProviders);
        await configApi.writeModelSlots(normalizedSlots, writtenProviders);
        const nextDrafts = {};
        for (const [currentProviderId, currentProvider] of Object.entries(writtenProviders)) {
          nextDrafts[currentProviderId] = providerDraftFromRecord(currentProvider);
        }
        setProviders(writtenProviders);
        setDrafts(nextDrafts);
      } catch (error) {
        setSaveErrors((previous) => ({
          ...previous,
          [providerId]: error instanceof Error ? error.message : String(error || "Provider could not be deleted."),
        }));
      } finally {
        setSavingId("");
      }
    },
    [providers],
  );

  const addCustomProvider = React.useCallback(() => {
    const provider = configApi.createCustomProvider(providers);
    setProviders((previous) => ({ ...previous, [provider.id]: provider }));
    setDrafts((previous) => ({ ...previous, [provider.id]: providerDraftFromRecord(provider) }));
  }, [providers]);

  return h("section", { className: "options-card" }, [
    h("div", { className: "section-header", key: "header" }, [
      h("div", { key: "copy" }, [
        h("div", { className: "section-eyebrow", key: "eyebrow" }, "Provider catalog"),
        h("h1", { className: "section-title", key: "title" }, "Providers"),
        h(
          "p",
          { className: "section-description", key: "description" },
          "Edit API keys, endpoints, and model lists here. This follows the reference sidebar-driven settings flow instead of hiding provider edits behind the startup gate.",
        ),
      ]),
      h(
        "button",
        {
          className: "options-button options-button-ghost",
          type: "button",
          onClick: addCustomProvider,
          key: "add",
        },
        "Add custom provider",
      ),
    ]),
    loading
      ? h("div", { className: "status-message", key: "loading" }, "Loading providers...")
      : h(
          "div",
          { className: "editor-list", key: "list" },
          orderedProviderIds.map((providerId) =>
            h(ProviderEditor, {
              provider: providers[providerId],
              draft: drafts[providerId] || providerDraftFromRecord(providers[providerId]),
              isFocused: focusedProviderId === providerId,
              isSaving: savingId === providerId,
              saveError: saveErrors[providerId],
              onChange: (nextDraft) => {
                setDrafts((previous) => ({
                  ...previous,
                  [providerId]: nextDraft,
                }));
              },
              onSave: () => void saveProvider(providerId),
              onDelete: () => void deleteProvider(providerId),
              key: providerId,
            }),
          ),
        ),
  ]);
}

function RoleCard({
  slotDef,
  slot,
  providers,
  onSlotChange,
  onEditProvider,
}) {
  const providerChoices = configApi.collectProviderChoices(providers, slotDef.id);
  const modelOptions = getSlotModelOptions(providers, slotDef.id, slot.providerId, slot.modelName);
  const provider = providers[slot.providerId];
  const setupStatus = configApi.getSlotSetupStatus(slotDef.id, { [slotDef.id]: slot }, providers);
  const current = configApi.getSlotDisplayLabel(slotDef.id, { [slotDef.id]: slot }, providers);

  return h("article", { className: `editor-card ${slotDef.requiredOnFirstStart && !setupStatus.ok ? "editor-card-warning" : ""}` }, [
    h("div", { className: "editor-header", key: "header" }, [
      h("div", { key: "copy" }, [
        h("h2", { className: "editor-title", key: "title" }, slotDef.label),
        h("div", { className: "editor-subtitle", key: "subtitle" }, slotDef.purpose || ""),
      ]),
      h("div", { className: "editor-pill-row", key: "pills" }, [
        h(StatusPill, { tone: setupStatus.ok ? "ready" : "warning", key: "status" }, setupStatus.ok ? "Ready" : "Needs setup"),
        h(StatusPill, { tone: "muted", key: "provider" }, provider?.name || slot.providerId || "Unset"),
      ]),
    ]),
    h(FieldRow, { label: "Provider", key: "providerField" }, h(
      "select",
      {
        className: "options-select",
        value: slot.providerId || "",
        disabled: slotDef.id === "target",
        onChange: (event) => {
          onSlotChange(slotDef.id, {
            providerId: event.target.value,
            modelName: "",
          });
        },
      },
      [
        slotDef.requiredOnFirstStart
          ? h("option", { value: "", key: "blank" }, "Choose provider")
          : null,
        ...providerChoices.map((choice) =>
          h("option", { value: choice.id, key: choice.id }, choice.label),
        ),
      ],
    )),
    h(FieldRow, { label: "Model", key: "modelField" }, h(
      "select",
      {
        className: "options-select",
        value: slot.modelName || "",
        disabled: modelOptions.length === 0,
        onChange: (event) => {
          onSlotChange(slotDef.id, {
            modelName: event.target.value,
          });
        },
      },
      modelOptions.length
        ? modelOptions.map((option) =>
            h("option", { value: option.modelName, key: option.modelName }, option.label),
          )
        : [h("option", { value: "", key: "empty" }, "No models configured for this provider")],
    )),
    slotDef.id === "target"
      ? null
      : h(FieldRow, { label: "Reasoning", key: "reasoningField" }, h(
          "select",
          {
            className: "options-select",
            value: String(slot.reasoningEffort || ""),
            onChange: (event) => {
              onSlotChange(slotDef.id, {
                reasoningEffort: event.target.value,
              });
            },
          },
          getReasoningOptions().map((option) =>
            h("option", { value: option.value, key: option.value || "off" }, option.label),
          ),
        )),
    h("div", { className: "status-line", key: "statusLine" }, [
      h("span", { className: "status-line-primary", key: "primary" }, current.value || "Unset"),
      h("span", { className: "status-line-secondary", key: "secondary" }, setupStatus.reason || "Ready."),
    ]),
    h("div", { className: "action-row", key: "actions" }, [
      provider?.id
        ? h(
            "button",
            {
              className: "options-button options-button-ghost",
              type: "button",
              onClick: () => onEditProvider(provider.id),
              key: "editProvider",
            },
            "Edit provider",
          )
        : null,
    ]),
  ]);
}

function ModelsSection({ configVersion, onEditProvider }) {
  const [providers, setProviders] = React.useState({});
  const [slots, setSlots] = React.useState(configApi.createDefaultModelSlots());
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState("");

  const loadState = React.useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const nextProviders = await configApi.readProviders();
      const nextSlots = await configApi.readModelSlots(nextProviders);
      setProviders(nextProviders);
      setSlots(nextSlots);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : String(loadError || "Models could not be loaded."));
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    void loadState();
  }, [loadState, configVersion]);

  const updateSlot = React.useCallback(
    async (slotId, patch) => {
      const nextSlots = configApi.patchModelSlot(slots, slotId, patch, providers);
      setSlots(nextSlots);
      setError("");
      try {
        const writtenSlots = await configApi.writeModelSlots(nextSlots, providers);
        setSlots(writtenSlots);
      } catch (saveError) {
        setError(saveError instanceof Error ? saveError.message : String(saveError || "Models could not be saved."));
      }
    },
    [providers, slots],
  );

  const setup = React.useMemo(
    () => configApi.getRequiredSetupStatus(slots, providers),
    [slots, providers],
  );

  return h("section", { className: "options-card" }, [
    h("div", { className: "section-header", key: "header" }, [
      h("div", { key: "copy" }, [
        h("div", { className: "section-eyebrow", key: "eyebrow" }, "Model roles"),
        h("h1", { className: "section-title", key: "title" }, "Models"),
        h(
          "p",
          { className: "section-description", key: "description" },
          "Choose the provider and model for each role. Provider editing stays one click away instead of being hidden behind the startup flow.",
        ),
      ]),
    ]),
    loading
      ? h("div", { className: "status-message", key: "loading" }, "Loading model roles...")
      : null,
    !loading && setup.ready
      ? h("div", { className: "setup-banner setup-banner-ready", key: "ready" }, [
          h("strong", { key: "title" }, "Required startup roles are configured."),
          h("span", { key: "body" }, setup.items.map((item) => item.label).join(" · ")),
        ])
      : null,
    !loading && !setup.ready
      ? h("div", { className: "setup-banner", key: "missing" }, [
          h("strong", { key: "title" }, "Agent, Batch, and Vision still need valid providers/models."),
          h(
            "div",
            { className: "setup-banner-list", key: "list" },
            setup.missingItems.map((item) =>
              h("span", { className: "setup-banner-chip", key: item.slotId }, `${item.label}: ${item.reason}`),
            ),
          ),
        ])
      : null,
    error ? h("div", { className: "status-message status-message-error", key: "error" }, error) : null,
    h(
      "div",
      { className: "editor-list", key: "list" },
      configApi.MODEL_SLOT_DEFS.map((slotDef) =>
        h(RoleCard, {
          slotDef,
          slot: slots[slotDef.id] || {},
          providers,
          onSlotChange: (slotId, patch) => void updateSlot(slotId, patch),
          onEditProvider,
          key: slotDef.id,
        }),
      ),
    ),
  ]);
}

function Sidebar({ sections, activeId, onSelect, themeId }) {
  const activeTheme = themeApi?.getTheme?.(themeId) || null;
  return h(
    "nav",
    {
      style: {
        width: 220,
        flex: "0 0 220px",
        borderRight: "1px solid var(--line)",
        padding: 12,
        minHeight: "100vh",
      },
    },
    h("div", {}, [
      h("div", { className: "options-brand-eyebrow", key: "eyebrow" }, "Fuck API, Train Local AI"),
      h("h2", { style: { margin: "8px 0 6px", fontSize: 28 }, key: "title" }, "Settings"),
      activeTheme
        ? h(
            "div",
            { style: { color: "var(--muted)", fontSize: 13, lineHeight: 1.45, marginBottom: 10 }, key: "copy" },
            `${activeTheme.title}. ${activeTheme.shortNote || activeTheme.description}`,
          )
        : null,
      ...sections.map((section) =>
        h(
          "button",
          {
            type: "button",
            onClick: () => onSelect(section.id),
            style: {
              display: "block",
              width: "100%",
              textAlign: "left",
              margin: "6px 0",
              padding: "10px 12px",
              background: section.id === activeId ? "var(--accent)" : "var(--surface-strong)",
              color: section.id === activeId ? "#fff" : "var(--text)",
              border: "1px solid var(--line)",
              borderRadius: 6,
              fontWeight: section.id === activeId ? 700 : 500,
            },
            key: section.id,
          },
          section.label,
        ),
      ),
    ]),
  );
}

function SectionHost({
  route,
  configVersion,
  themeId,
  focusedProviderId,
  onThemeChange,
  onJumpToSection,
}) {
  const activeSection = route.section;
  if (activeSection === "general") {
    return h(GeneralSection, { themeId, onThemeChange, configVersion });
  }
  if (activeSection === "providers") {
    return h(ProvidersSection, { configVersion, focusedProviderId });
  }
  if (activeSection === "models") {
    return h(ModelsSection, {
      configVersion,
      onEditProvider: (providerId) => onJumpToSection("providers", providerId),
    });
  }
  if (activeSection === "share") {
    return h(ShareSection);
  }
  return null;
}

function OptionsApp({ initialThemeId }) {
  const [route, updateRoute] = usePageRoute();
  const [themeId, setThemeId] = React.useState(initialThemeId);
  const [configVersion, setConfigVersion] = React.useState(0);
  const [focusedProviderId, setFocusedProviderId] = React.useState("");

  const handleThemeChange = React.useCallback(async (nextThemeId) => {
    const normalizedThemeId = themeApi?.normalizeThemeId?.(nextThemeId) || nextThemeId;
    setThemeId(normalizedThemeId);
    themeApi?.applyTheme?.(normalizedThemeId);
    try {
      await themeApi?.writeTheme?.(normalizedThemeId);
    } catch (_error) {
      // keep UI responsive even when persistence fails
    }
  }, []);

  const handleJumpToSection = React.useCallback(
    (sectionId, providerId = "") => {
      if (sectionId === "providers" || sectionId === "models") {
        setConfigVersion((version) => version + 1);
      }
      setFocusedProviderId(sectionId === "providers" ? providerId : "");
      updateRoute({ section: sectionId });
    },
    [updateRoute],
  );

  return h("div", { className: "options-app" }, [
    h(Sidebar, {
      sections: SECTION_DEFS,
      activeId: route.section,
      onSelect: (sectionId) => {
        setFocusedProviderId("");
        updateRoute({ section: sectionId });
      },
      themeId,
      key: "sidebar",
    }),
    h("main", { style: { flex: 1, padding: 16, minWidth: 0 }, key: "main" }, [
      h("div", { className: "options-stack", key: "stack" }, [
        h(SectionHost, {
          route,
          configVersion,
          themeId,
          focusedProviderId,
          onThemeChange: handleThemeChange,
          onJumpToSection: handleJumpToSection,
          key: route.section,
        }),
      ]),
    ]),
  ]);
}

function redirectLegacyWorkspaceRoute() {
  try {
    const url = new URL(location.href);
    const legacySection =
      normalizeLegacyWorkspaceSection(url.searchParams.get("section")) ||
      normalizeLegacyWorkspaceSection(String(location.hash || "").replace(/^#/, "").split("/")[0]);
    const craftId = String(url.searchParams.get("craft") || "").trim();
    if (!legacySection || !craftId) {
      return false;
    }
    const targetTab =
      legacySection === "training-data"
        ? "training-data"
        : normalizeLegacyCraftTab(url.searchParams.get("bundleTab"));
    location.replace(buildCraftPageUrl(craftId, targetTab));
    return true;
  } catch (_error) {
    return false;
  }
}

async function init() {
  if (redirectLegacyWorkspaceRoute()) {
    return;
  }

  await ensureCraftSyncLoaded();

  let initialThemeId = themeApi?.DEFAULT_THEME_ID || "copyshop";
  try {
    initialThemeId = (await themeApi?.hydrateTheme?.()) || initialThemeId;
  } catch (_error) {
    themeApi?.applyTheme?.(initialThemeId);
  }

  const appContainer = document.querySelector("#app-container");
  if (!appContainer) {
    throw new Error("Can not find #app-container");
  }
  const root = clientExports.createRoot(appContainer);
  root.render(h(OptionsApp, { initialThemeId }));
}

void init();
