// Origin: CTOX
// License: Apache-2.0
//
// Compact policy: two-layer compaction control for CTOX sessions.
//
// LAYER 1 — Emergency compaction (hard limit)
//   This is only valid for clean-break follow-up compaction. Mid-task
//   compaction must not fire merely because a turn read a lot of context:
//   that is exactly what tool-heavy work is supposed to do, and a post-call
//   token event is too late to prevent the already-sent call from overflowing.
//
// LAYER 2 — Adaptive compaction (context-drift signal)
//   Ratio of model-generated output tokens to tool-loaded input tokens.
//   When the model starts producing disproportionately more text relative to
//   what it reads from tools, it indicates context drift (repetition, loss of
//   task binding). Compacting at this point sharpens the context.
//
// Both layers can fire independently. Emergency always takes priority.

use ctox_protocol::protocol::EventMsg;

/// Emergency compaction fires at this fraction of context_window.
/// 0.75 means: when the per-call input reaches 75% of the window, compact
/// immediately. This leaves headroom for large tool outputs and local backend
/// tokenization drift before the next request is assembled without aborting
/// normal large task prompts before the model can answer.
/// Works at any window size (128K, 256K, etc.).
const DEFAULT_EMERGENCY_FILL_RATIO: f64 = 0.75;
const DEFAULT_ADAPTIVE_MIN_OUTPUT_TOKENS: i64 = 4_096;

/// How to compact.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompactMode {
    /// ThreadCompactStart on the live thread. Preserves the running session.
    MidTask,
    /// ThreadUnsubscribe + enqueue follow-up slice. Clean break.
    ForcedFollowup,
}

/// Why compact was requested.
#[derive(Debug, Clone, PartialEq)]
pub enum CompactReason {
    /// Hard limit: per-call input reached emergency fill ratio of window.
    Emergency {
        input_tokens: i64,
        context_window: i64,
        fill_ratio: f64,
    },
    /// Adaptive: model's self-generated output share of context exceeded threshold.
    SelfOutputRatio {
        output_tokens: i64,
        total_context_tokens: i64,
        actual_pct: u32,
        threshold_pct: u32,
    },
    /// Fixed-turn trigger.
    TurnCount {
        turns_since_last: u32,
        target_n: u32,
    },
}

/// What to do.
#[derive(Debug, Clone, PartialEq)]
pub enum CompactDecision {
    Continue,
    Compact { reason: CompactReason },
}

/// Trigger configuration.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CompactTrigger {
    /// No adaptive or fixed trigger (emergency still fires).
    Off,
    /// Fire when the model's own output tokens make up more than this
    /// percentage of the per-call input context. E.g. 15 means 15%.
    /// If the model has written >= 15% of what it receives, it's drifting.
    /// TUI range: 5–25, default 15. Stored as integer percentage (no floats).
    Adaptive { self_output_pct: u32 },
    /// Fire every N turns.
    FixedTurns { n: u32 },
}

/// Policy state machine.
#[derive(Debug, Clone)]
pub struct CompactPolicy {
    pub trigger: CompactTrigger,
    pub mode: CompactMode,
    /// Emergency compaction fires when per-call input tokens exceed this
    /// fraction of the context window. Default 0.75 (75%).
    pub emergency_fill_ratio: f64,
    /// Context window size (learned from first TurnStarted/TokenCount event).
    pub context_window: i64,
    turns_since_last_compact: u32,
    /// Per-call input tokens (actual context size sent to model).
    pub last_call_input_tokens: i64,
    /// Cumulative output tokens generated by the model.
    cum_output_tokens: i64,
    /// Cumulative input tokens loaded from tool results.
    /// Approximated as: total_input - first_call_input (baseline prompt).
    cum_tool_input_tokens: i64,
    /// Approximate input tokens returned by tools during this turn. This is
    /// the read side of the adaptive "writes instead of reads" signal.
    observed_tool_input_tokens: i64,
    /// The input tokens from the very first call (baseline prompt size).
    baseline_input: Option<i64>,
    /// Guard: suppress ALL compact decisions until next TurnComplete.
    /// Set after any compact fires. Cleared on TurnComplete.
    suppressed_until_turn_end: bool,
}

impl CompactPolicy {
    pub fn new(trigger: CompactTrigger, mode: CompactMode) -> Self {
        Self {
            trigger,
            mode,
            emergency_fill_ratio: DEFAULT_EMERGENCY_FILL_RATIO,
            context_window: 131_072, // CTOX default; overridden by from_settings
            turns_since_last_compact: 0,
            last_call_input_tokens: 0,
            cum_output_tokens: 0,
            cum_tool_input_tokens: 0,
            observed_tool_input_tokens: 0,
            baseline_input: None,
            suppressed_until_turn_end: false,
        }
    }

    pub fn from_settings(
        trigger_raw: Option<&str>,
        mode_raw: Option<&str>,
        fixed_n_raw: Option<&str>,
        drift_threshold_raw: Option<&str>,
        emergency_ratio_raw: Option<&str>,
        context_window_raw: Option<&str>,
    ) -> Self {
        let trigger = match trigger_raw
            .map(str::trim)
            .map(str::to_ascii_lowercase)
            .as_deref()
        {
            Some("adaptive") => {
                let pct = drift_threshold_raw
                    .and_then(|v| v.trim().parse::<u32>().ok())
                    .unwrap_or(15); // default 15%
                CompactTrigger::Adaptive {
                    self_output_pct: pct.clamp(1, 100),
                }
            }
            Some("fixed") => {
                let n = fixed_n_raw
                    .and_then(|v| v.trim().parse::<u32>().ok())
                    .unwrap_or(0);
                if n == 0 {
                    CompactTrigger::Off
                } else {
                    CompactTrigger::FixedTurns { n }
                }
            }
            Some("off") => CompactTrigger::Off,
            // Default = Adaptive(15%). The adaptive output/input drift signal
            // is the only mid-task trigger that catches drift before the
            // per-call input grows large enough to need an emergency. Leaving
            // the default at Off (the previous behaviour) silently disabled
            // both layers and let long worker cycles run unprotected until
            // they overflowed the context window.
            _ => CompactTrigger::Adaptive {
                self_output_pct: 15,
            },
        };
        let mode = match mode_raw
            .map(str::trim)
            .map(str::to_ascii_lowercase)
            .as_deref()
        {
            Some("forced-followup") | Some("forced_followup") => CompactMode::ForcedFollowup,
            _ => CompactMode::MidTask,
        };
        let emergency_ratio = emergency_ratio_raw
            .and_then(|v| v.trim().parse::<f64>().ok())
            .filter(|v| *v >= 0.5 && *v <= 1.0)
            .unwrap_or(DEFAULT_EMERGENCY_FILL_RATIO);
        let context_window = context_window_raw
            .and_then(|v| v.trim().parse::<i64>().ok())
            .unwrap_or(131_072); // CTOX_CHAT_MODEL_MAX_CONTEXT default
        let mut policy = Self::new(trigger, mode);
        policy.emergency_fill_ratio = emergency_ratio;
        policy.context_window = context_window;
        policy
    }

    /// Called for every decoded EventMsg.
    pub fn evaluate(&mut self, event: &EventMsg) -> CompactDecision {
        match event {
            EventMsg::TokenCount(tc) => {
                if let Some(info) = tc.info.as_ref() {
                    if let Some(window) = info.model_context_window.filter(|value| *value > 0) {
                        self.context_window = window;
                    }
                    let last_input = info.last_token_usage.input_tokens;
                    self.last_call_input_tokens = last_input;
                    // For the adaptive self-output ratio, count only visible
                    // output tokens — exclude reasoning tokens. Reasoning
                    // tokens (M2.7, o-series) inflate the output count but
                    // don't represent context drift. Without this, reasoning-
                    // heavy models hit the adaptive threshold prematurely
                    // while non-reasoning models don't, making comparison
                    // between model families unfair.
                    let total_out = info.total_token_usage.output_tokens;
                    let reasoning_out = info.total_token_usage.reasoning_output_tokens;
                    self.cum_output_tokens = (total_out - reasoning_out).max(0);

                    if self.baseline_input.is_none() {
                        self.baseline_input = Some(last_input);
                    }
                    let baseline = self.baseline_input.unwrap_or(0);
                    self.cum_tool_input_tokens =
                        (info.total_token_usage.input_tokens - baseline).max(0);
                }
                // After a compact fires, suppress ALL further compacts until
                // TurnComplete. This prevents re-fire loops (cumulative
                // counters don't decrease within a turn).
                if self.suppressed_until_turn_end {
                    return CompactDecision::Continue;
                }
                // Layer 1: Emergency — per-call input approaching window.
                // Fires in BOTH modes: a per-call input near the context limit
                // is a hard overflow risk regardless of whether the cycle is
                // mid-task or at a clean break. The previous implementation
                // skipped the check in MidTask mode, which let long
                // tool-loops (SWE-Bench, large workspaces) climb past 100% of
                // the window and crash the inference call with a 400
                // exceed_context_size_error. With this guard active, MidTask
                // compaction triggers a ThreadCompactStart and ForcedFollowup
                // triggers a clean-break unsubscribe — both handled in the
                // direct-session loop.
                if self.context_window > 0 {
                    let fill = (self.last_call_input_tokens as f64) / (self.context_window as f64);
                    if fill >= self.emergency_fill_ratio {
                        return CompactDecision::Compact {
                            reason: CompactReason::Emergency {
                                input_tokens: self.last_call_input_tokens,
                                context_window: self.context_window,
                                fill_ratio: fill,
                            },
                        };
                    }
                }
                // Layer 2: Adaptive self-output ratio.
                self.check_self_output_ratio()
            }
            EventMsg::ExecCommandEnd(ev) => {
                let text = if ev.formatted_output.is_empty() {
                    format!("{}{}", ev.stdout, ev.stderr)
                } else {
                    ev.formatted_output.clone()
                };
                self.observed_tool_input_tokens = self
                    .observed_tool_input_tokens
                    .saturating_add(approx_tokens(&text));
                CompactDecision::Continue
            }
            EventMsg::McpToolCallEnd(ev) => {
                let text = match &ev.result {
                    Ok(result) => serde_json::to_string(result).unwrap_or_default(),
                    Err(err) => err.clone(),
                };
                self.observed_tool_input_tokens = self
                    .observed_tool_input_tokens
                    .saturating_add(approx_tokens(&text));
                CompactDecision::Continue
            }
            EventMsg::DynamicToolCallResponse(ev) => {
                let mut text = serde_json::to_string(&ev.content_items).unwrap_or_default();
                if let Some(err) = &ev.error {
                    text.push_str(err);
                }
                self.observed_tool_input_tokens = self
                    .observed_tool_input_tokens
                    .saturating_add(approx_tokens(&text));
                CompactDecision::Continue
            }
            EventMsg::TurnComplete(_) => {
                self.turns_since_last_compact = self.turns_since_last_compact.saturating_add(1);
                self.suppressed_until_turn_end = false; // clear for next turn
                self.check_fixed_turns()
            }
            _ => CompactDecision::Continue,
        }
    }

    /// Mark that a compact was sent. Suppress further compacts until TurnComplete.
    pub fn note_compacted(&mut self) {
        self.turns_since_last_compact = 0;
        self.suppressed_until_turn_end = true;
    }

    fn check_self_output_ratio(&self) -> CompactDecision {
        let CompactTrigger::Adaptive {
            self_output_pct: threshold_pct,
        } = self.trigger
        else {
            return CompactDecision::Continue;
        };
        if self.cum_output_tokens < DEFAULT_ADAPTIVE_MIN_OUTPUT_TOKENS {
            return CompactDecision::Continue;
        }
        let read_input_tokens = self
            .observed_tool_input_tokens
            .max(self.cum_tool_input_tokens)
            .max(1);
        // Integer arithmetic: (output * 100) / read_input >= threshold_pct.
        // No floating point, no ratio conversion, no ambiguity.
        let actual_pct = ((self.cum_output_tokens * 100) / read_input_tokens) as u32;
        if actual_pct >= threshold_pct {
            CompactDecision::Compact {
                reason: CompactReason::SelfOutputRatio {
                    output_tokens: self.cum_output_tokens,
                    total_context_tokens: read_input_tokens,
                    actual_pct,
                    threshold_pct,
                },
            }
        } else {
            CompactDecision::Continue
        }
    }

    fn check_fixed_turns(&self) -> CompactDecision {
        let CompactTrigger::FixedTurns { n } = self.trigger else {
            return CompactDecision::Continue;
        };
        if n == 0 {
            return CompactDecision::Continue;
        }
        if self.turns_since_last_compact >= n {
            CompactDecision::Compact {
                reason: CompactReason::TurnCount {
                    turns_since_last: self.turns_since_last_compact,
                    target_n: n,
                },
            }
        } else {
            CompactDecision::Continue
        }
    }
}

fn approx_tokens(text: &str) -> i64 {
    ((text.chars().count() as i64) / 4).max(0)
}

impl CompactReason {
    pub fn log_summary(&self) -> String {
        match self {
            CompactReason::Emergency {
                input_tokens,
                context_window,
                fill_ratio,
            } => {
                let pct = (fill_ratio * 100.0).round() as u32;
                format!("EMERGENCY input={input_tokens}/{context_window} fill={pct}%")
            }
            CompactReason::SelfOutputRatio {
                output_tokens,
                total_context_tokens,
                actual_pct,
                threshold_pct,
            } => {
                format!(
                    "self-output {output_tokens}/{total_context_tokens} = {actual_pct}% >= {threshold_pct}%"
                )
            }
            CompactReason::TurnCount {
                turns_since_last,
                target_n,
            } => {
                format!("turn-count {turns_since_last}/{target_n}")
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ctox_protocol::protocol::{TokenCountEvent, TokenUsage, TokenUsageInfo, TurnCompleteEvent};

    fn token_event(
        cum_in: i64,
        cum_out: i64,
        last_in: i64,
        last_out: i64,
        window: i64,
    ) -> EventMsg {
        EventMsg::TokenCount(TokenCountEvent {
            info: Some(TokenUsageInfo {
                total_token_usage: TokenUsage {
                    input_tokens: cum_in,
                    cached_input_tokens: 0,
                    output_tokens: cum_out,
                    reasoning_output_tokens: 0,
                    total_tokens: cum_in + cum_out,
                },
                last_token_usage: TokenUsage {
                    input_tokens: last_in,
                    cached_input_tokens: 0,
                    output_tokens: last_out,
                    reasoning_output_tokens: 0,
                    total_tokens: last_in + last_out,
                },
                model_context_window: Some(window),
            }),
            rate_limits: None,
        })
    }

    #[test]
    fn emergency_fires_at_fill_ratio() {
        let mut p = CompactPolicy::new(CompactTrigger::Off, CompactMode::ForcedFollowup);
        // emergency_fill_ratio = 0.75 default. 75% of 131072 = 98304.
        // First call sets baseline (small input → no fire)
        assert_eq!(
            p.evaluate(&token_event(10000, 500, 10000, 500, 131072)),
            CompactDecision::Continue
        );
        // Per-call input reaches 100K (> 98304) -> EMERGENCY
        let dec = p.evaluate(&token_event(200000, 5000, 100_000, 500, 131072));
        assert!(matches!(
            dec,
            CompactDecision::Compact {
                reason: CompactReason::Emergency { .. }
            }
        ));
    }

    #[test]
    fn emergency_ratio_override_rejects_too_low_values() {
        let p = CompactPolicy::from_settings(
            Some("off"),
            Some("forced-followup"),
            None,
            None,
            Some("0.20"),
            Some("131072"),
        );

        assert_eq!(p.emergency_fill_ratio, DEFAULT_EMERGENCY_FILL_RATIO);
    }

    #[test]
    fn emergency_does_not_refire_while_in_flight() {
        let mut p = CompactPolicy::new(CompactTrigger::Off, CompactMode::ForcedFollowup);
        p.evaluate(&token_event(10000, 500, 10000, 500, 131072)); // baseline
        let _ = p.evaluate(&token_event(200000, 5000, 100_000, 500, 131072)); // fires
        p.note_compacted();
        // Still at 100K but in-flight → suppressed
        assert_eq!(
            p.evaluate(&token_event(210000, 5500, 100_000, 500, 131072)),
            CompactDecision::Continue
        );
        // Drops below the threshold → still suppressed until turn end, so no re-fire.
        assert_eq!(
            p.evaluate(&token_event(260000, 6000, 50000, 500, 131072)),
            CompactDecision::Continue
        );
        assert!(p.suppressed_until_turn_end);
        assert_eq!(
            p.evaluate(&EventMsg::TurnComplete(TurnCompleteEvent {
                turn_id: "t".into(),
                last_agent_message: None,
            })),
            CompactDecision::Continue
        );
        assert!(!p.suppressed_until_turn_end);
    }

    #[test]
    fn midtask_emergency_fires_when_per_call_input_exceeds_window_fill() {
        // Updated semantics: emergency fires in BOTH MidTask and
        // ForcedFollowup modes. Per-call input over the configured fill
        // ratio is a real overflow risk regardless of mode, and skipping
        // the check in MidTask used to let tool-heavy turns crash the
        // inference call with exceed_context_size_error.
        let mut p = CompactPolicy::new(CompactTrigger::Off, CompactMode::MidTask);
        p.context_window = 32_768;

        // First call sets baseline (small input → no fire).
        assert_eq!(
            p.evaluate(&token_event(5_000, 300, 5_000, 300, 32_768)),
            CompactDecision::Continue
        );
        // Per-call input climbs over 75% of 32_768 (= 24_576) -> EMERGENCY
        // even in MidTask mode.
        let dec = p.evaluate(&token_event(37_404, 600, 30_000, 300, 32_768));
        assert!(matches!(
            dec,
            CompactDecision::Compact {
                reason: CompactReason::Emergency { .. }
            }
        ));
    }

    #[test]
    fn emergency_uses_model_reported_context_window_over_settings_fallback() {
        let mut p = CompactPolicy::new(CompactTrigger::Off, CompactMode::ForcedFollowup);
        p.context_window = 32_768;

        assert_eq!(
            p.evaluate(&token_event(37_404, 300, 37_404, 300, 272_000)),
            CompactDecision::Continue
        );
        assert_eq!(p.context_window, 272_000);
    }

    #[test]
    fn adaptive_fires_on_self_output_pct() {
        // Threshold 15%: fire when model's cumulative output >= 15% of per-call input.
        let mut p = CompactPolicy::new(
            CompactTrigger::Adaptive {
                self_output_pct: 15,
            },
            CompactMode::MidTask,
        );
        // cum_out=500, call_input=10K → 500*100/10000=5% < 15%
        assert_eq!(
            p.evaluate(&token_event(10000, 500, 10000, 500, 131072)),
            CompactDecision::Continue
        );
        // cum_out=2000, call_input=20K → 2000*100/20000=10% < 15%
        assert_eq!(
            p.evaluate(&token_event(30000, 2000, 20000, 1500, 131072)),
            CompactDecision::Continue
        );
        // cum_out=5000, read_input=20K → 5000*100/20000=25% >= 15% → FIRE
        let dec = p.evaluate(&token_event(30000, 5000, 25000, 3000, 131072));
        assert!(matches!(
            dec,
            CompactDecision::Compact {
                reason: CompactReason::SelfOutputRatio { .. }
            }
        ));
    }

    #[test]
    fn fixed_turns_fires_on_nth_complete() {
        let mut p = CompactPolicy::new(CompactTrigger::FixedTurns { n: 2 }, CompactMode::MidTask);
        let tc = EventMsg::TurnComplete(TurnCompleteEvent {
            turn_id: "t".into(),
            last_agent_message: None,
        });
        assert_eq!(p.evaluate(&tc), CompactDecision::Continue);
        let dec = p.evaluate(&tc);
        assert!(matches!(
            dec,
            CompactDecision::Compact {
                reason: CompactReason::TurnCount { .. }
            }
        ));
    }
}
