export const collections = {
  desktop_icons: {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: { type: 'string', maxLength: 128 },
      target_type: { type: 'string' },
      target_module: { type: 'string' },
      target_record_id: { type: 'string' },
      label: { type: 'string' },
      glyph: { type: 'string' },
      x: { type: 'number' },
      y: { type: 'number' },
      pinned: { type: 'boolean' },
      hidden: { type: 'boolean' },
      sort_index: { type: 'number' },
      updated_at_ms: { type: 'number' },
    },
    required: ['id', 'target_type', 'updated_at_ms'],
    additionalProperties: true,
  },
  desktop_layout: {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: { type: 'string', maxLength: 64 },
      desktop_style: { type: 'string' },
      wallpaper_url: { type: 'string' },
      wallpaper_mode: { type: 'string' },
      taskbar_pins: { type: 'array', items: { type: 'string' } },
      tray_config: { type: 'object', additionalProperties: true },
      menubar_apps: { type: 'array', items: { type: 'string' } },
      grid_cell_w: { type: 'number' },
      grid_cell_h: { type: 'number' },
      grid_offset: { type: 'number' },
      updated_at_ms: { type: 'number' },
    },
    required: ['id', 'updated_at_ms'],
    additionalProperties: true,
  },
  desktop_notifications: {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: { type: 'string', maxLength: 128 },
      command_id: { type: 'string' },
      module: { type: 'string' },
      type: { type: 'string' },
      title: { type: 'string' },
      message: { type: 'string' },
      action_label: { type: 'string' },
      action_module: { type: 'string' },
      action_record_id: { type: 'string' },
      created_at_ms: { type: 'number' },
      read_at_ms: { type: 'number' },
      dismissed_at_ms: { type: 'number' },
    },
    required: ['id', 'created_at_ms'],
    additionalProperties: true,
  },
  desktop_files: {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: { type: 'string', maxLength: 160 },
      parent_id: { type: 'string' },
      path: { type: 'string' },
      local_path: { type: 'string' },
      virtual_path: { type: 'string' },
      name: { type: 'string' },
      kind: { type: 'string' },
      mime_type: { type: 'string' },
      extension: { type: 'string' },
      size_bytes: { type: 'number' },
      owner_id: { type: 'string' },
      source: { type: 'string' },
      linked_collection: { type: 'string' },
      linked_record_id: { type: 'string' },
      content_ref: { type: 'string' },
      content_state: { type: 'string' },
      content_hash: { type: 'string' },
      mtime_ms: { type: 'number' },
      content_synced_at_ms: { type: 'number' },
      sort_index: { type: 'number' },
      is_deleted: { type: 'boolean' },
      created_at_ms: { type: 'number' },
      updated_at_ms: { type: 'number' },
    },
    required: ['id', 'name', 'kind', 'created_at_ms', 'updated_at_ms'],
    additionalProperties: true,
  },
  desktop_file_chunks: {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: { type: 'string', maxLength: 180 },
      file_id: { type: 'string' },
      idx: { type: 'number' },
      total: { type: 'number' },
      encoding: { type: 'string' },
      data: { type: 'string' },
      size_bytes: { type: 'number' },
      created_at_ms: { type: 'number' },
    },
    required: ['id', 'file_id', 'idx', 'total', 'encoding', 'data', 'created_at_ms'],
    additionalProperties: true,
  },
  communication_accounts: {
    version: 0,
    primaryKey: 'account_key',
    type: 'object',
    properties: {
      account_key: { type: 'string', maxLength: 256 },
      channel: { type: 'string' },
      address: { type: 'string' },
      provider: { type: 'string' },
      profile_json: { type: 'object', additionalProperties: true },
      created_at: { type: 'string' },
      updated_at: { type: 'string' },
      last_inbound_ok_at: { type: 'string' },
      last_outbound_ok_at: { type: 'string' },
      updated_at_ms: { type: 'number' },
      is_deleted: { type: 'boolean' },
      deleted_at_ms: { type: 'number' },
    },
    required: ['account_key', 'channel', 'address', 'provider', 'created_at', 'updated_at'],
    additionalProperties: true,
  },
  channel_pairing_state: {
    version: 0,
    primaryKey: 'channel',
    type: 'object',
    properties: {
      channel: { type: 'string', maxLength: 64 },
      status: { type: 'string' },
      qr_payload: { type: 'string' },
      qr_svg: { type: 'string' },
      account_key: { type: 'string' },
      error: { type: 'string' },
      step: { type: 'string' },
      updated_at_ms: { type: 'number' },
    },
    required: ['channel', 'status', 'updated_at_ms'],
    additionalProperties: true,
  },
  desktop_windows: {
    version: 0,
    primaryKey: 'id',
    type: 'object',
    properties: {
      id: { type: 'string', maxLength: 256 },
      owner_id: { type: 'string', maxLength: 256 },
      title: { type: 'string' },
      icon: { type: 'string' },
      x: { type: 'number' },
      y: { type: 'number' },
      width: { type: 'number' },
      height: { type: 'number' },
      state: { type: 'string' },
      snap_zone: { type: 'string' },
      always_on_top: { type: 'boolean' },
      stored_x: { type: 'number' },
      stored_y: { type: 'number' },
      stored_width: { type: 'number' },
      stored_height: { type: 'number' },
      updated_at_ms: { type: 'number' },
    },
    required: ['id', 'owner_id', 'updated_at_ms'],
    additionalProperties: true,
  },
};

export const migrationStrategies = {};
