const browserSessionSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 160 },
    owner_user_id: { type: 'string' },
    controller_user_id: { type: 'string' },
    status: { type: 'string' },
    runtime_status: { type: 'string' },
    current_tab_id: { type: 'string' },
    current_url: { type: 'string' },
    title: { type: 'string' },
    viewport_w: { type: 'number' },
    viewport_h: { type: 'number' },
    device_scale_factor: { type: 'number' },
    frame_rate_target: { type: 'number' },
    active_frame_id: { type: 'string' },
    last_frame_seq: { type: 'number' },
    last_input_seq: { type: 'number' },
    pending_input_count: { type: 'number' },
    error: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
  },
  required: ['id', 'status', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'updated_at_ms',
    ['status', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const browserTabSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 180 },
    session_id: { type: 'string' },
    title: { type: 'string' },
    url: { type: 'string' },
    status: { type: 'string' },
    loading: { type: 'boolean' },
    active: { type: 'boolean' },
    can_go_back: { type: 'boolean' },
    can_go_forward: { type: 'boolean' },
    frame_seq: { type: 'number' },
    last_frame_id: { type: 'string' },
    last_frame_at_ms: { type: 'number' },
    error: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
  },
  required: ['id', 'session_id', 'status', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'session_id',
    ['session_id', 'updated_at_ms'],
  ],
  additionalProperties: true,
};

const browserFrameSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 220 },
    session_id: { type: 'string' },
    tab_id: { type: 'string' },
    seq: { type: 'number' },
    mime_type: { type: 'string' },
    encoding: { type: 'string' },
    data: { type: 'string' },
    width: { type: 'number' },
    height: { type: 'number' },
    viewport_w: { type: 'number' },
    viewport_h: { type: 'number' },
    quality: { type: 'number' },
    size_bytes: { type: 'number' },
    frame_hash: { type: 'string' },
    captured_at_ms: { type: 'number' },
    expires_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
  },
  required: [
    'id',
    'session_id',
    'tab_id',
    'seq',
    'mime_type',
    'encoding',
    'data',
    'width',
    'height',
    'captured_at_ms',
    'expires_at_ms',
    'updated_at_ms',
  ],
  indexes: [
    'session_id',
    ['session_id', 'seq'],
    ['session_id', 'expires_at_ms'],
    ['tab_id', 'seq'],
  ],
  additionalProperties: true,
};

const browserInputEventSchema = {
  version: 0,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 220 },
    session_id: { type: 'string' },
    tab_id: { type: 'string' },
    seq: { type: 'number' },
    type: { type: 'string' },
    status: { type: 'string' },
    x: { type: 'number' },
    y: { type: 'number' },
    button: { type: 'string' },
    buttons: { type: 'number' },
    dx: { type: 'number' },
    dy: { type: 'number' },
    key: { type: 'string' },
    code: { type: 'string' },
    modifiers: { type: 'array', items: { type: 'string' } },
    text: { type: 'string' },
    payload: { type: 'object', additionalProperties: true },
    consumed_at_ms: { type: 'number' },
    error: { type: 'string' },
    created_at_ms: { type: 'number' },
    updated_at_ms: { type: 'number' },
  },
  required: ['id', 'session_id', 'seq', 'type', 'status', 'created_at_ms', 'updated_at_ms'],
  indexes: [
    'session_id',
    ['session_id', 'seq'],
    ['status', 'created_at_ms'],
  ],
  additionalProperties: true,
};

export const collections = {
  browser_sessions: browserSessionSchema,
  browser_tabs: browserTabSchema,
  browser_frames: browserFrameSchema,
  browser_input_events: browserInputEventSchema,
};
